// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register_device.proto

package edu.buffalo.cse.ubwins.cellmon;

public final class RegisterDeviceOuterClass {
  private RegisterDeviceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisterDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegisterDevice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    java.lang.String getIMEIHASH();
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    com.google.protobuf.ByteString
        getIMEIHASHBytes();

    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    java.lang.String getBOARD();
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    com.google.protobuf.ByteString
        getBOARDBytes();

    /**
     * <code>optional string BRAND = 3;</code>
     */
    java.lang.String getBRAND();
    /**
     * <code>optional string BRAND = 3;</code>
     */
    com.google.protobuf.ByteString
        getBRANDBytes();

    /**
     * <code>optional string DEVICE = 4;</code>
     */
    java.lang.String getDEVICE();
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    com.google.protobuf.ByteString
        getDEVICEBytes();

    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    java.lang.String getHARDWARE();
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    com.google.protobuf.ByteString
        getHARDWAREBytes();

    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    java.lang.String getMANUFACTURER();
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    com.google.protobuf.ByteString
        getMANUFACTURERBytes();

    /**
     * <code>optional string MODEL = 7;</code>
     */
    java.lang.String getMODEL();
    /**
     * <code>optional string MODEL = 7;</code>
     */
    com.google.protobuf.ByteString
        getMODELBytes();

    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    java.lang.String getPRODUCT();
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    com.google.protobuf.ByteString
        getPRODUCTBytes();

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    java.lang.String getNETWORKCOUNTRYISO();
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKCOUNTRYISOBytes();

    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    java.lang.String getNETWORKOPERATORCODE();
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKOPERATORCODEBytes();

    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    java.lang.String getNETWORKOPERATORNAME();
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKOPERATORNAMEBytes();

    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    java.lang.String getPHONETYPE();
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    com.google.protobuf.ByteString
        getPHONETYPEBytes();

    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    java.lang.String getSIMCOUNTRYISO();
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    com.google.protobuf.ByteString
        getSIMCOUNTRYISOBytes();

    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    java.lang.String getSIMOPERATOR();
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    com.google.protobuf.ByteString
        getSIMOPERATORBytes();

    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    java.lang.String getSIMOPERATORNAME();
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    com.google.protobuf.ByteString
        getSIMOPERATORNAMEBytes();

    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    java.lang.String getRELEASE();
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    com.google.protobuf.ByteString
        getRELEASEBytes();

    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    java.lang.String getSDKINT();
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    com.google.protobuf.ByteString
        getSDKINTBytes();
  }
  /**
   * Protobuf type {@code RegisterDevice}
   */
  public  static final class RegisterDevice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RegisterDevice)
      RegisterDeviceOrBuilder {
    // Use RegisterDevice.newBuilder() to construct.
    private RegisterDevice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterDevice() {
      iMEIHASH_ = "";
      bOARD_ = "";
      bRAND_ = "";
      dEVICE_ = "";
      hARDWARE_ = "";
      mANUFACTURER_ = "";
      mODEL_ = "";
      pRODUCT_ = "";
      nETWORKCOUNTRYISO_ = "";
      nETWORKOPERATORCODE_ = "";
      nETWORKOPERATORNAME_ = "";
      pHONETYPE_ = "";
      sIMCOUNTRYISO_ = "";
      sIMOPERATOR_ = "";
      sIMOPERATORNAME_ = "";
      rELEASE_ = "";
      sDKINT_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RegisterDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              iMEIHASH_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              bOARD_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              bRAND_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              dEVICE_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              hARDWARE_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              mANUFACTURER_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              mODEL_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              pRODUCT_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              nETWORKCOUNTRYISO_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              nETWORKOPERATORCODE_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              nETWORKOPERATORNAME_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              pHONETYPE_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              sIMCOUNTRYISO_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              sIMOPERATOR_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              sIMOPERATORNAME_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              rELEASE_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              sDKINT_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.internal_static_RegisterDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.internal_static_RegisterDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.class, edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.Builder.class);
    }

    public static final int IMEI_HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object iMEIHASH_;
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public java.lang.String getIMEIHASH() {
      java.lang.Object ref = iMEIHASH_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iMEIHASH_ = s;
        return s;
      }
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIMEIHASHBytes() {
      java.lang.Object ref = iMEIHASH_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iMEIHASH_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOARD_FIELD_NUMBER = 2;
    private volatile java.lang.Object bOARD_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    public java.lang.String getBOARD() {
      java.lang.Object ref = bOARD_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bOARD_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBOARDBytes() {
      java.lang.Object ref = bOARD_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bOARD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object bRAND_;
    /**
     * <code>optional string BRAND = 3;</code>
     */
    public java.lang.String getBRAND() {
      java.lang.Object ref = bRAND_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bRAND_ = s;
        return s;
      }
    }
    /**
     * <code>optional string BRAND = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBRANDBytes() {
      java.lang.Object ref = bRAND_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bRAND_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_FIELD_NUMBER = 4;
    private volatile java.lang.Object dEVICE_;
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    public java.lang.String getDEVICE() {
      java.lang.Object ref = dEVICE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dEVICE_ = s;
        return s;
      }
    }
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDEVICEBytes() {
      java.lang.Object ref = dEVICE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dEVICE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWARE_FIELD_NUMBER = 5;
    private volatile java.lang.Object hARDWARE_;
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    public java.lang.String getHARDWARE() {
      java.lang.Object ref = hARDWARE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hARDWARE_ = s;
        return s;
      }
    }
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHARDWAREBytes() {
      java.lang.Object ref = hARDWARE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hARDWARE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANUFACTURER_FIELD_NUMBER = 6;
    private volatile java.lang.Object mANUFACTURER_;
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    public java.lang.String getMANUFACTURER() {
      java.lang.Object ref = mANUFACTURER_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mANUFACTURER_ = s;
        return s;
      }
    }
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMANUFACTURERBytes() {
      java.lang.Object ref = mANUFACTURER_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mANUFACTURER_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 7;
    private volatile java.lang.Object mODEL_;
    /**
     * <code>optional string MODEL = 7;</code>
     */
    public java.lang.String getMODEL() {
      java.lang.Object ref = mODEL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mODEL_ = s;
        return s;
      }
    }
    /**
     * <code>optional string MODEL = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMODELBytes() {
      java.lang.Object ref = mODEL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mODEL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_FIELD_NUMBER = 8;
    private volatile java.lang.Object pRODUCT_;
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    public java.lang.String getPRODUCT() {
      java.lang.Object ref = pRODUCT_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pRODUCT_ = s;
        return s;
      }
    }
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPRODUCTBytes() {
      java.lang.Object ref = pRODUCT_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pRODUCT_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETWORK_COUNTRY_ISO_FIELD_NUMBER = 9;
    private volatile java.lang.Object nETWORKCOUNTRYISO_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    public java.lang.String getNETWORKCOUNTRYISO() {
      java.lang.Object ref = nETWORKCOUNTRYISO_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nETWORKCOUNTRYISO_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKCOUNTRYISOBytes() {
      java.lang.Object ref = nETWORKCOUNTRYISO_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nETWORKCOUNTRYISO_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETWORK_OPERATOR_CODE_FIELD_NUMBER = 10;
    private volatile java.lang.Object nETWORKOPERATORCODE_;
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    public java.lang.String getNETWORKOPERATORCODE() {
      java.lang.Object ref = nETWORKOPERATORCODE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nETWORKOPERATORCODE_ = s;
        return s;
      }
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKOPERATORCODEBytes() {
      java.lang.Object ref = nETWORKOPERATORCODE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nETWORKOPERATORCODE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETWORK_OPERATOR_NAME_FIELD_NUMBER = 11;
    private volatile java.lang.Object nETWORKOPERATORNAME_;
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    public java.lang.String getNETWORKOPERATORNAME() {
      java.lang.Object ref = nETWORKOPERATORNAME_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nETWORKOPERATORNAME_ = s;
        return s;
      }
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKOPERATORNAMEBytes() {
      java.lang.Object ref = nETWORKOPERATORNAME_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nETWORKOPERATORNAME_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_TYPE_FIELD_NUMBER = 12;
    private volatile java.lang.Object pHONETYPE_;
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    public java.lang.String getPHONETYPE() {
      java.lang.Object ref = pHONETYPE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pHONETYPE_ = s;
        return s;
      }
    }
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    public com.google.protobuf.ByteString
        getPHONETYPEBytes() {
      java.lang.Object ref = pHONETYPE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pHONETYPE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIM_COUNTRY_ISO_FIELD_NUMBER = 13;
    private volatile java.lang.Object sIMCOUNTRYISO_;
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    public java.lang.String getSIMCOUNTRYISO() {
      java.lang.Object ref = sIMCOUNTRYISO_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sIMCOUNTRYISO_ = s;
        return s;
      }
    }
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    public com.google.protobuf.ByteString
        getSIMCOUNTRYISOBytes() {
      java.lang.Object ref = sIMCOUNTRYISO_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sIMCOUNTRYISO_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIM_OPERATOR_FIELD_NUMBER = 14;
    private volatile java.lang.Object sIMOPERATOR_;
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    public java.lang.String getSIMOPERATOR() {
      java.lang.Object ref = sIMOPERATOR_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sIMOPERATOR_ = s;
        return s;
      }
    }
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    public com.google.protobuf.ByteString
        getSIMOPERATORBytes() {
      java.lang.Object ref = sIMOPERATOR_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sIMOPERATOR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIM_OPERATOR_NAME_FIELD_NUMBER = 15;
    private volatile java.lang.Object sIMOPERATORNAME_;
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    public java.lang.String getSIMOPERATORNAME() {
      java.lang.Object ref = sIMOPERATORNAME_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sIMOPERATORNAME_ = s;
        return s;
      }
    }
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    public com.google.protobuf.ByteString
        getSIMOPERATORNAMEBytes() {
      java.lang.Object ref = sIMOPERATORNAME_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sIMOPERATORNAME_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELEASE_FIELD_NUMBER = 16;
    private volatile java.lang.Object rELEASE_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    public java.lang.String getRELEASE() {
      java.lang.Object ref = rELEASE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rELEASE_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    public com.google.protobuf.ByteString
        getRELEASEBytes() {
      java.lang.Object ref = rELEASE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rELEASE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDK_INT_FIELD_NUMBER = 17;
    private volatile java.lang.Object sDKINT_;
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    public java.lang.String getSDKINT() {
      java.lang.Object ref = sDKINT_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sDKINT_ = s;
        return s;
      }
    }
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    public com.google.protobuf.ByteString
        getSDKINTBytes() {
      java.lang.Object ref = sDKINT_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sDKINT_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIMEIHASHBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, iMEIHASH_);
      }
      if (!getBOARDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bOARD_);
      }
      if (!getBRANDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bRAND_);
      }
      if (!getDEVICEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dEVICE_);
      }
      if (!getHARDWAREBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hARDWARE_);
      }
      if (!getMANUFACTURERBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mANUFACTURER_);
      }
      if (!getMODELBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, mODEL_);
      }
      if (!getPRODUCTBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pRODUCT_);
      }
      if (!getNETWORKCOUNTRYISOBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, nETWORKCOUNTRYISO_);
      }
      if (!getNETWORKOPERATORCODEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, nETWORKOPERATORCODE_);
      }
      if (!getNETWORKOPERATORNAMEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, nETWORKOPERATORNAME_);
      }
      if (!getPHONETYPEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, pHONETYPE_);
      }
      if (!getSIMCOUNTRYISOBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, sIMCOUNTRYISO_);
      }
      if (!getSIMOPERATORBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, sIMOPERATOR_);
      }
      if (!getSIMOPERATORNAMEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, sIMOPERATORNAME_);
      }
      if (!getRELEASEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, rELEASE_);
      }
      if (!getSDKINTBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, sDKINT_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIMEIHASHBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, iMEIHASH_);
      }
      if (!getBOARDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bOARD_);
      }
      if (!getBRANDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bRAND_);
      }
      if (!getDEVICEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dEVICE_);
      }
      if (!getHARDWAREBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, hARDWARE_);
      }
      if (!getMANUFACTURERBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mANUFACTURER_);
      }
      if (!getMODELBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, mODEL_);
      }
      if (!getPRODUCTBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pRODUCT_);
      }
      if (!getNETWORKCOUNTRYISOBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, nETWORKCOUNTRYISO_);
      }
      if (!getNETWORKOPERATORCODEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, nETWORKOPERATORCODE_);
      }
      if (!getNETWORKOPERATORNAMEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, nETWORKOPERATORNAME_);
      }
      if (!getPHONETYPEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, pHONETYPE_);
      }
      if (!getSIMCOUNTRYISOBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, sIMCOUNTRYISO_);
      }
      if (!getSIMOPERATORBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, sIMOPERATOR_);
      }
      if (!getSIMOPERATORNAMEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, sIMOPERATORNAME_);
      }
      if (!getRELEASEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, rELEASE_);
      }
      if (!getSDKINTBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, sDKINT_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice)) {
        return super.equals(obj);
      }
      edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice other = (edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice) obj;

      boolean result = true;
      result = result && getIMEIHASH()
          .equals(other.getIMEIHASH());
      result = result && getBOARD()
          .equals(other.getBOARD());
      result = result && getBRAND()
          .equals(other.getBRAND());
      result = result && getDEVICE()
          .equals(other.getDEVICE());
      result = result && getHARDWARE()
          .equals(other.getHARDWARE());
      result = result && getMANUFACTURER()
          .equals(other.getMANUFACTURER());
      result = result && getMODEL()
          .equals(other.getMODEL());
      result = result && getPRODUCT()
          .equals(other.getPRODUCT());
      result = result && getNETWORKCOUNTRYISO()
          .equals(other.getNETWORKCOUNTRYISO());
      result = result && getNETWORKOPERATORCODE()
          .equals(other.getNETWORKOPERATORCODE());
      result = result && getNETWORKOPERATORNAME()
          .equals(other.getNETWORKOPERATORNAME());
      result = result && getPHONETYPE()
          .equals(other.getPHONETYPE());
      result = result && getSIMCOUNTRYISO()
          .equals(other.getSIMCOUNTRYISO());
      result = result && getSIMOPERATOR()
          .equals(other.getSIMOPERATOR());
      result = result && getSIMOPERATORNAME()
          .equals(other.getSIMOPERATORNAME());
      result = result && getRELEASE()
          .equals(other.getRELEASE());
      result = result && getSDKINT()
          .equals(other.getSDKINT());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IMEI_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getIMEIHASH().hashCode();
      hash = (37 * hash) + BOARD_FIELD_NUMBER;
      hash = (53 * hash) + getBOARD().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBRAND().hashCode();
      hash = (37 * hash) + DEVICE_FIELD_NUMBER;
      hash = (53 * hash) + getDEVICE().hashCode();
      hash = (37 * hash) + HARDWARE_FIELD_NUMBER;
      hash = (53 * hash) + getHARDWARE().hashCode();
      hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
      hash = (53 * hash) + getMANUFACTURER().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getMODEL().hashCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getPRODUCT().hashCode();
      hash = (37 * hash) + NETWORK_COUNTRY_ISO_FIELD_NUMBER;
      hash = (53 * hash) + getNETWORKCOUNTRYISO().hashCode();
      hash = (37 * hash) + NETWORK_OPERATOR_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getNETWORKOPERATORCODE().hashCode();
      hash = (37 * hash) + NETWORK_OPERATOR_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getNETWORKOPERATORNAME().hashCode();
      hash = (37 * hash) + PHONE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPHONETYPE().hashCode();
      hash = (37 * hash) + SIM_COUNTRY_ISO_FIELD_NUMBER;
      hash = (53 * hash) + getSIMCOUNTRYISO().hashCode();
      hash = (37 * hash) + SIM_OPERATOR_FIELD_NUMBER;
      hash = (53 * hash) + getSIMOPERATOR().hashCode();
      hash = (37 * hash) + SIM_OPERATOR_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSIMOPERATORNAME().hashCode();
      hash = (37 * hash) + RELEASE_FIELD_NUMBER;
      hash = (53 * hash) + getRELEASE().hashCode();
      hash = (37 * hash) + SDK_INT_FIELD_NUMBER;
      hash = (53 * hash) + getSDKINT().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegisterDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RegisterDevice)
        edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.internal_static_RegisterDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.internal_static_RegisterDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.class, edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.Builder.class);
      }

      // Construct using edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iMEIHASH_ = "";

        bOARD_ = "";

        bRAND_ = "";

        dEVICE_ = "";

        hARDWARE_ = "";

        mANUFACTURER_ = "";

        mODEL_ = "";

        pRODUCT_ = "";

        nETWORKCOUNTRYISO_ = "";

        nETWORKOPERATORCODE_ = "";

        nETWORKOPERATORNAME_ = "";

        pHONETYPE_ = "";

        sIMCOUNTRYISO_ = "";

        sIMOPERATOR_ = "";

        sIMOPERATORNAME_ = "";

        rELEASE_ = "";

        sDKINT_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.internal_static_RegisterDevice_descriptor;
      }

      public edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice getDefaultInstanceForType() {
        return edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.getDefaultInstance();
      }

      public edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice build() {
        edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice buildPartial() {
        edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice result = new edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice(this);
        result.iMEIHASH_ = iMEIHASH_;
        result.bOARD_ = bOARD_;
        result.bRAND_ = bRAND_;
        result.dEVICE_ = dEVICE_;
        result.hARDWARE_ = hARDWARE_;
        result.mANUFACTURER_ = mANUFACTURER_;
        result.mODEL_ = mODEL_;
        result.pRODUCT_ = pRODUCT_;
        result.nETWORKCOUNTRYISO_ = nETWORKCOUNTRYISO_;
        result.nETWORKOPERATORCODE_ = nETWORKOPERATORCODE_;
        result.nETWORKOPERATORNAME_ = nETWORKOPERATORNAME_;
        result.pHONETYPE_ = pHONETYPE_;
        result.sIMCOUNTRYISO_ = sIMCOUNTRYISO_;
        result.sIMOPERATOR_ = sIMOPERATOR_;
        result.sIMOPERATORNAME_ = sIMOPERATORNAME_;
        result.rELEASE_ = rELEASE_;
        result.sDKINT_ = sDKINT_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice) {
          return mergeFrom((edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice other) {
        if (other == edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.getDefaultInstance()) return this;
        if (!other.getIMEIHASH().isEmpty()) {
          iMEIHASH_ = other.iMEIHASH_;
          onChanged();
        }
        if (!other.getBOARD().isEmpty()) {
          bOARD_ = other.bOARD_;
          onChanged();
        }
        if (!other.getBRAND().isEmpty()) {
          bRAND_ = other.bRAND_;
          onChanged();
        }
        if (!other.getDEVICE().isEmpty()) {
          dEVICE_ = other.dEVICE_;
          onChanged();
        }
        if (!other.getHARDWARE().isEmpty()) {
          hARDWARE_ = other.hARDWARE_;
          onChanged();
        }
        if (!other.getMANUFACTURER().isEmpty()) {
          mANUFACTURER_ = other.mANUFACTURER_;
          onChanged();
        }
        if (!other.getMODEL().isEmpty()) {
          mODEL_ = other.mODEL_;
          onChanged();
        }
        if (!other.getPRODUCT().isEmpty()) {
          pRODUCT_ = other.pRODUCT_;
          onChanged();
        }
        if (!other.getNETWORKCOUNTRYISO().isEmpty()) {
          nETWORKCOUNTRYISO_ = other.nETWORKCOUNTRYISO_;
          onChanged();
        }
        if (!other.getNETWORKOPERATORCODE().isEmpty()) {
          nETWORKOPERATORCODE_ = other.nETWORKOPERATORCODE_;
          onChanged();
        }
        if (!other.getNETWORKOPERATORNAME().isEmpty()) {
          nETWORKOPERATORNAME_ = other.nETWORKOPERATORNAME_;
          onChanged();
        }
        if (!other.getPHONETYPE().isEmpty()) {
          pHONETYPE_ = other.pHONETYPE_;
          onChanged();
        }
        if (!other.getSIMCOUNTRYISO().isEmpty()) {
          sIMCOUNTRYISO_ = other.sIMCOUNTRYISO_;
          onChanged();
        }
        if (!other.getSIMOPERATOR().isEmpty()) {
          sIMOPERATOR_ = other.sIMOPERATOR_;
          onChanged();
        }
        if (!other.getSIMOPERATORNAME().isEmpty()) {
          sIMOPERATORNAME_ = other.sIMOPERATORNAME_;
          onChanged();
        }
        if (!other.getRELEASE().isEmpty()) {
          rELEASE_ = other.rELEASE_;
          onChanged();
        }
        if (!other.getSDKINT().isEmpty()) {
          sDKINT_ = other.sDKINT_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object iMEIHASH_ = "";
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public java.lang.String getIMEIHASH() {
        java.lang.Object ref = iMEIHASH_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iMEIHASH_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIMEIHASHBytes() {
        java.lang.Object ref = iMEIHASH_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iMEIHASH_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASH(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iMEIHASH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder clearIMEIHASH() {
        
        iMEIHASH_ = getDefaultInstance().getIMEIHASH();
        onChanged();
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASHBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iMEIHASH_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bOARD_ = "";
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public java.lang.String getBOARD() {
        java.lang.Object ref = bOARD_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bOARD_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBOARDBytes() {
        java.lang.Object ref = bOARD_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bOARD_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public Builder setBOARD(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bOARD_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public Builder clearBOARD() {
        
        bOARD_ = getDefaultInstance().getBOARD();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public Builder setBOARDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bOARD_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bRAND_ = "";
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public java.lang.String getBRAND() {
        java.lang.Object ref = bRAND_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bRAND_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBRANDBytes() {
        java.lang.Object ref = bRAND_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bRAND_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public Builder setBRAND(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bRAND_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public Builder clearBRAND() {
        
        bRAND_ = getDefaultInstance().getBRAND();
        onChanged();
        return this;
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public Builder setBRANDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bRAND_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dEVICE_ = "";
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public java.lang.String getDEVICE() {
        java.lang.Object ref = dEVICE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dEVICE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDEVICEBytes() {
        java.lang.Object ref = dEVICE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dEVICE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public Builder setDEVICE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dEVICE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public Builder clearDEVICE() {
        
        dEVICE_ = getDefaultInstance().getDEVICE();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public Builder setDEVICEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dEVICE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hARDWARE_ = "";
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public java.lang.String getHARDWARE() {
        java.lang.Object ref = hARDWARE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hARDWARE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHARDWAREBytes() {
        java.lang.Object ref = hARDWARE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hARDWARE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public Builder setHARDWARE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hARDWARE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public Builder clearHARDWARE() {
        
        hARDWARE_ = getDefaultInstance().getHARDWARE();
        onChanged();
        return this;
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public Builder setHARDWAREBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hARDWARE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mANUFACTURER_ = "";
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public java.lang.String getMANUFACTURER() {
        java.lang.Object ref = mANUFACTURER_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mANUFACTURER_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMANUFACTURERBytes() {
        java.lang.Object ref = mANUFACTURER_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mANUFACTURER_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public Builder setMANUFACTURER(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mANUFACTURER_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public Builder clearMANUFACTURER() {
        
        mANUFACTURER_ = getDefaultInstance().getMANUFACTURER();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public Builder setMANUFACTURERBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mANUFACTURER_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mODEL_ = "";
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public java.lang.String getMODEL() {
        java.lang.Object ref = mODEL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mODEL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMODELBytes() {
        java.lang.Object ref = mODEL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mODEL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public Builder setMODEL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mODEL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public Builder clearMODEL() {
        
        mODEL_ = getDefaultInstance().getMODEL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public Builder setMODELBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mODEL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pRODUCT_ = "";
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public java.lang.String getPRODUCT() {
        java.lang.Object ref = pRODUCT_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pRODUCT_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPRODUCTBytes() {
        java.lang.Object ref = pRODUCT_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pRODUCT_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public Builder setPRODUCT(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pRODUCT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public Builder clearPRODUCT() {
        
        pRODUCT_ = getDefaultInstance().getPRODUCT();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public Builder setPRODUCTBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pRODUCT_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nETWORKCOUNTRYISO_ = "";
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public java.lang.String getNETWORKCOUNTRYISO() {
        java.lang.Object ref = nETWORKCOUNTRYISO_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nETWORKCOUNTRYISO_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKCOUNTRYISOBytes() {
        java.lang.Object ref = nETWORKCOUNTRYISO_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nETWORKCOUNTRYISO_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public Builder setNETWORKCOUNTRYISO(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nETWORKCOUNTRYISO_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public Builder clearNETWORKCOUNTRYISO() {
        
        nETWORKCOUNTRYISO_ = getDefaultInstance().getNETWORKCOUNTRYISO();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public Builder setNETWORKCOUNTRYISOBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nETWORKCOUNTRYISO_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nETWORKOPERATORCODE_ = "";
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public java.lang.String getNETWORKOPERATORCODE() {
        java.lang.Object ref = nETWORKOPERATORCODE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nETWORKOPERATORCODE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKOPERATORCODEBytes() {
        java.lang.Object ref = nETWORKOPERATORCODE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nETWORKOPERATORCODE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public Builder setNETWORKOPERATORCODE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nETWORKOPERATORCODE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public Builder clearNETWORKOPERATORCODE() {
        
        nETWORKOPERATORCODE_ = getDefaultInstance().getNETWORKOPERATORCODE();
        onChanged();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public Builder setNETWORKOPERATORCODEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nETWORKOPERATORCODE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nETWORKOPERATORNAME_ = "";
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public java.lang.String getNETWORKOPERATORNAME() {
        java.lang.Object ref = nETWORKOPERATORNAME_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nETWORKOPERATORNAME_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKOPERATORNAMEBytes() {
        java.lang.Object ref = nETWORKOPERATORNAME_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nETWORKOPERATORNAME_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public Builder setNETWORKOPERATORNAME(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nETWORKOPERATORNAME_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public Builder clearNETWORKOPERATORNAME() {
        
        nETWORKOPERATORNAME_ = getDefaultInstance().getNETWORKOPERATORNAME();
        onChanged();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public Builder setNETWORKOPERATORNAMEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nETWORKOPERATORNAME_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pHONETYPE_ = "";
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public java.lang.String getPHONETYPE() {
        java.lang.Object ref = pHONETYPE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pHONETYPE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPHONETYPEBytes() {
        java.lang.Object ref = pHONETYPE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pHONETYPE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public Builder setPHONETYPE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pHONETYPE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public Builder clearPHONETYPE() {
        
        pHONETYPE_ = getDefaultInstance().getPHONETYPE();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public Builder setPHONETYPEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pHONETYPE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sIMCOUNTRYISO_ = "";
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public java.lang.String getSIMCOUNTRYISO() {
        java.lang.Object ref = sIMCOUNTRYISO_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sIMCOUNTRYISO_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public com.google.protobuf.ByteString
          getSIMCOUNTRYISOBytes() {
        java.lang.Object ref = sIMCOUNTRYISO_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sIMCOUNTRYISO_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public Builder setSIMCOUNTRYISO(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sIMCOUNTRYISO_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public Builder clearSIMCOUNTRYISO() {
        
        sIMCOUNTRYISO_ = getDefaultInstance().getSIMCOUNTRYISO();
        onChanged();
        return this;
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public Builder setSIMCOUNTRYISOBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sIMCOUNTRYISO_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sIMOPERATOR_ = "";
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public java.lang.String getSIMOPERATOR() {
        java.lang.Object ref = sIMOPERATOR_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sIMOPERATOR_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public com.google.protobuf.ByteString
          getSIMOPERATORBytes() {
        java.lang.Object ref = sIMOPERATOR_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sIMOPERATOR_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public Builder setSIMOPERATOR(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sIMOPERATOR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public Builder clearSIMOPERATOR() {
        
        sIMOPERATOR_ = getDefaultInstance().getSIMOPERATOR();
        onChanged();
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public Builder setSIMOPERATORBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sIMOPERATOR_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sIMOPERATORNAME_ = "";
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public java.lang.String getSIMOPERATORNAME() {
        java.lang.Object ref = sIMOPERATORNAME_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sIMOPERATORNAME_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public com.google.protobuf.ByteString
          getSIMOPERATORNAMEBytes() {
        java.lang.Object ref = sIMOPERATORNAME_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sIMOPERATORNAME_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public Builder setSIMOPERATORNAME(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sIMOPERATORNAME_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public Builder clearSIMOPERATORNAME() {
        
        sIMOPERATORNAME_ = getDefaultInstance().getSIMOPERATORNAME();
        onChanged();
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public Builder setSIMOPERATORNAMEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sIMOPERATORNAME_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rELEASE_ = "";
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public java.lang.String getRELEASE() {
        java.lang.Object ref = rELEASE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rELEASE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public com.google.protobuf.ByteString
          getRELEASEBytes() {
        java.lang.Object ref = rELEASE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rELEASE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public Builder setRELEASE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rELEASE_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public Builder clearRELEASE() {
        
        rELEASE_ = getDefaultInstance().getRELEASE();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public Builder setRELEASEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rELEASE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sDKINT_ = "";
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public java.lang.String getSDKINT() {
        java.lang.Object ref = sDKINT_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sDKINT_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public com.google.protobuf.ByteString
          getSDKINTBytes() {
        java.lang.Object ref = sDKINT_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sDKINT_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public Builder setSDKINT(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sDKINT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public Builder clearSDKINT() {
        
        sDKINT_ = getDefaultInstance().getSDKINT();
        onChanged();
        return this;
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public Builder setSDKINTBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sDKINT_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RegisterDevice)
    }

    // @@protoc_insertion_point(class_scope:RegisterDevice)
    private static final edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice();
    }

    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterDevice>
        PARSER = new com.google.protobuf.AbstractParser<RegisterDevice>() {
      public RegisterDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RegisterDevice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterDevice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterDevice> getParserForType() {
      return PARSER;
    }

    public edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterDevice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterDevice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025register_device.proto\"\364\002\n\016RegisterDevi" +
      "ce\022\021\n\tIMEI_HASH\030\001 \001(\t\022\r\n\005BOARD\030\002 \001(\t\022\r\n\005" +
      "BRAND\030\003 \001(\t\022\016\n\006DEVICE\030\004 \001(\t\022\020\n\010HARDWARE\030" +
      "\005 \001(\t\022\024\n\014MANUFACTURER\030\006 \001(\t\022\r\n\005MODEL\030\007 \001" +
      "(\t\022\017\n\007PRODUCT\030\010 \001(\t\022\033\n\023NETWORK_COUNTRY_I" +
      "SO\030\t \001(\t\022\035\n\025NETWORK_OPERATOR_CODE\030\n \001(\t\022" +
      "\035\n\025NETWORK_OPERATOR_NAME\030\013 \001(\t\022\022\n\nPHONE_" +
      "TYPE\030\014 \001(\t\022\027\n\017SIM_COUNTRY_ISO\030\r \001(\t\022\024\n\014S" +
      "IM_OPERATOR\030\016 \001(\t\022\031\n\021SIM_OPERATOR_NAME\030\017" +
      " \001(\t\022\017\n\007RELEASE\030\020 \001(\t\022\017\n\007SDK_INT\030\021 \001(\tB1",
      "\n/ubcomputerscience.ubwins.cellularnetwo" +
      "rkmonitorb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegisterDevice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterDevice_descriptor,
        new java.lang.String[] { "IMEIHASH", "BOARD", "BRAND", "DEVICE", "HARDWARE", "MANUFACTURER", "MODEL", "PRODUCT", "NETWORKCOUNTRYISO", "NETWORKOPERATORCODE", "NETWORKOPERATORNAME", "PHONETYPE", "SIMCOUNTRYISO", "SIMOPERATOR", "SIMOPERATORNAME", "RELEASE", "SDKINT", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
