// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_record.proto

package edu.buffalo.cse.ubwins.cellmon;

public final class DataRecordOuterClass {
  private DataRecordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DataEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataEntry)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    long getTIMESTAMP();

    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    double getFUSEDLAT();

    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    double getFUSEDLONG();

    /**
     * <code>optional bool STALE = 4;</code>
     */
    boolean getSTALE();

    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    int getNETWORKTYPEValue();
    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType getNETWORKTYPE();

    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    int getNETWORKCELLTYPEValue();
    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType getNETWORKCELLTYPE();

    /**
     * <pre>
     * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
     * </pre>
     *
     * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
     */
    int getNETWORKPARAM1();

    /**
     * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
     */
    int getNETWORKPARAM2();

    /**
     * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
     */
    int getNETWORKPARAM3();

    /**
     * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
     */
    int getNETWORKPARAM4();

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
     * </pre>
     *
     * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
     */
    int getSIGNALASULEVEL();

    /**
     * <code>optional sint32 SIGNAL_DBM = 12;</code>
     */
    int getSIGNALDBM();

    /**
     * <code>optional int32 SIGNAL_LEVEL = 13;</code>
     */
    int getSIGNALLEVEL();

    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    int getNETWORKSTATEValue();
    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState getNETWORKSTATE();

    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    int getNETWORKDATAACTIVITYValue();
    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity getNETWORKDATAACTIVITY();

    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    int getVOICECALLSTATEValue();
    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity getVOICECALLSTATE();
  }
  /**
   * Protobuf type {@code DataEntry}
   */
  public  static final class DataEntry extends
      com.google.protobuf.GeneratedMessageLite<
          DataEntry, DataEntry.Builder> implements
      // @@protoc_insertion_point(message_implements:DataEntry)
      DataEntryOrBuilder {
    private DataEntry() {
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * Protobuf enum {@code DataEntry.NetType}
     */
    public enum NetType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>NETWORK_TYPE_UNKNOWN = 0;</code>
       */
      NETWORK_TYPE_UNKNOWN(0),
      /**
       * <code>NETWORK_TYPE_GPRS = 1;</code>
       */
      NETWORK_TYPE_GPRS(1),
      /**
       * <code>NETWORK_TYPE_EDGE = 2;</code>
       */
      NETWORK_TYPE_EDGE(2),
      /**
       * <code>NETWORK_TYPE_UMTS = 3;</code>
       */
      NETWORK_TYPE_UMTS(3),
      /**
       * <code>NETWORK_TYPE_HSDPA = 4;</code>
       */
      NETWORK_TYPE_HSDPA(4),
      /**
       * <code>NETWORK_TYPE_HSUPA = 5;</code>
       */
      NETWORK_TYPE_HSUPA(5),
      /**
       * <code>NETWORK_TYPE_HSPA = 6;</code>
       */
      NETWORK_TYPE_HSPA(6),
      /**
       * <code>NETWORK_TYPE_CDMA = 7;</code>
       */
      NETWORK_TYPE_CDMA(7),
      /**
       * <code>NETWORK_TYPE_EVDO_0 = 8;</code>
       */
      NETWORK_TYPE_EVDO_0(8),
      /**
       * <code>NETWORK_TYPE_EVDO_A = 9;</code>
       */
      NETWORK_TYPE_EVDO_A(9),
      /**
       * <code>NETWORK_TYPE_EVDO_B = 10;</code>
       */
      NETWORK_TYPE_EVDO_B(10),
      /**
       * <code>NETWORK_TYPE_1xRTT = 11;</code>
       */
      NETWORK_TYPE_1xRTT(11),
      /**
       * <code>NETWORK_TYPE_IDEN = 12;</code>
       */
      NETWORK_TYPE_IDEN(12),
      /**
       * <code>NETWORK_TYPE_LTE = 13;</code>
       */
      NETWORK_TYPE_LTE(13),
      /**
       * <code>NETWORK_TYPE_EHRPD = 14;</code>
       */
      NETWORK_TYPE_EHRPD(14),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NETWORK_TYPE_UNKNOWN = 0;</code>
       */
      public static final int NETWORK_TYPE_UNKNOWN_VALUE = 0;
      /**
       * <code>NETWORK_TYPE_GPRS = 1;</code>
       */
      public static final int NETWORK_TYPE_GPRS_VALUE = 1;
      /**
       * <code>NETWORK_TYPE_EDGE = 2;</code>
       */
      public static final int NETWORK_TYPE_EDGE_VALUE = 2;
      /**
       * <code>NETWORK_TYPE_UMTS = 3;</code>
       */
      public static final int NETWORK_TYPE_UMTS_VALUE = 3;
      /**
       * <code>NETWORK_TYPE_HSDPA = 4;</code>
       */
      public static final int NETWORK_TYPE_HSDPA_VALUE = 4;
      /**
       * <code>NETWORK_TYPE_HSUPA = 5;</code>
       */
      public static final int NETWORK_TYPE_HSUPA_VALUE = 5;
      /**
       * <code>NETWORK_TYPE_HSPA = 6;</code>
       */
      public static final int NETWORK_TYPE_HSPA_VALUE = 6;
      /**
       * <code>NETWORK_TYPE_CDMA = 7;</code>
       */
      public static final int NETWORK_TYPE_CDMA_VALUE = 7;
      /**
       * <code>NETWORK_TYPE_EVDO_0 = 8;</code>
       */
      public static final int NETWORK_TYPE_EVDO_0_VALUE = 8;
      /**
       * <code>NETWORK_TYPE_EVDO_A = 9;</code>
       */
      public static final int NETWORK_TYPE_EVDO_A_VALUE = 9;
      /**
       * <code>NETWORK_TYPE_EVDO_B = 10;</code>
       */
      public static final int NETWORK_TYPE_EVDO_B_VALUE = 10;
      /**
       * <code>NETWORK_TYPE_1xRTT = 11;</code>
       */
      public static final int NETWORK_TYPE_1xRTT_VALUE = 11;
      /**
       * <code>NETWORK_TYPE_IDEN = 12;</code>
       */
      public static final int NETWORK_TYPE_IDEN_VALUE = 12;
      /**
       * <code>NETWORK_TYPE_LTE = 13;</code>
       */
      public static final int NETWORK_TYPE_LTE_VALUE = 13;
      /**
       * <code>NETWORK_TYPE_EHRPD = 14;</code>
       */
      public static final int NETWORK_TYPE_EHRPD_VALUE = 14;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NetType valueOf(int value) {
        return forNumber(value);
      }

      public static NetType forNumber(int value) {
        switch (value) {
          case 0: return NETWORK_TYPE_UNKNOWN;
          case 1: return NETWORK_TYPE_GPRS;
          case 2: return NETWORK_TYPE_EDGE;
          case 3: return NETWORK_TYPE_UMTS;
          case 4: return NETWORK_TYPE_HSDPA;
          case 5: return NETWORK_TYPE_HSUPA;
          case 6: return NETWORK_TYPE_HSPA;
          case 7: return NETWORK_TYPE_CDMA;
          case 8: return NETWORK_TYPE_EVDO_0;
          case 9: return NETWORK_TYPE_EVDO_A;
          case 10: return NETWORK_TYPE_EVDO_B;
          case 11: return NETWORK_TYPE_1xRTT;
          case 12: return NETWORK_TYPE_IDEN;
          case 13: return NETWORK_TYPE_LTE;
          case 14: return NETWORK_TYPE_EHRPD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NetType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetType>() {
              public NetType findValueByNumber(int number) {
                return NetType.forNumber(number);
              }
            };

      private final int value;

      private NetType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntry.NetType)
    }

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
     * </pre>
     *
     * Protobuf enum {@code DataEntry.CellType}
     */
    public enum CellType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>GSM = 0;</code>
       */
      GSM(0),
      /**
       * <code>CDMA = 1;</code>
       */
      CDMA(1),
      /**
       * <code>WCDMA = 2;</code>
       */
      WCDMA(2),
      /**
       * <code>LTE = 3;</code>
       */
      LTE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GSM = 0;</code>
       */
      public static final int GSM_VALUE = 0;
      /**
       * <code>CDMA = 1;</code>
       */
      public static final int CDMA_VALUE = 1;
      /**
       * <code>WCDMA = 2;</code>
       */
      public static final int WCDMA_VALUE = 2;
      /**
       * <code>LTE = 3;</code>
       */
      public static final int LTE_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CellType valueOf(int value) {
        return forNumber(value);
      }

      public static CellType forNumber(int value) {
        switch (value) {
          case 0: return GSM;
          case 1: return CDMA;
          case 2: return WCDMA;
          case 3: return LTE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CellType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CellType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CellType>() {
              public CellType findValueByNumber(int number) {
                return CellType.forNumber(number);
              }
            };

      private final int value;

      private CellType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntry.CellType)
    }

    /**
     * <pre>
     * https://developer.android.com/reference/android/net/NetworkInfo.DetailedState.html 
     * </pre>
     *
     * Protobuf enum {@code DataEntry.NetState}
     */
    public enum NetState
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>IDLE = 1;</code>
       */
      IDLE(1),
      /**
       * <code>SCANNING = 2;</code>
       */
      SCANNING(2),
      /**
       * <code>CONNECTING = 3;</code>
       */
      CONNECTING(3),
      /**
       * <code>AUTHENTICATING = 4;</code>
       */
      AUTHENTICATING(4),
      /**
       * <code>OBTAINING_IPADDR = 5;</code>
       */
      OBTAINING_IPADDR(5),
      /**
       * <code>CONNECTED = 6;</code>
       */
      CONNECTED(6),
      /**
       * <code>SUSPENDED = 7;</code>
       */
      SUSPENDED(7),
      /**
       * <code>DISCONNECTING = 8;</code>
       */
      DISCONNECTING(8),
      /**
       * <code>DISCONNECTED = 9;</code>
       */
      DISCONNECTED(9),
      /**
       * <code>FAILED = 10;</code>
       */
      FAILED(10),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>IDLE = 1;</code>
       */
      public static final int IDLE_VALUE = 1;
      /**
       * <code>SCANNING = 2;</code>
       */
      public static final int SCANNING_VALUE = 2;
      /**
       * <code>CONNECTING = 3;</code>
       */
      public static final int CONNECTING_VALUE = 3;
      /**
       * <code>AUTHENTICATING = 4;</code>
       */
      public static final int AUTHENTICATING_VALUE = 4;
      /**
       * <code>OBTAINING_IPADDR = 5;</code>
       */
      public static final int OBTAINING_IPADDR_VALUE = 5;
      /**
       * <code>CONNECTED = 6;</code>
       */
      public static final int CONNECTED_VALUE = 6;
      /**
       * <code>SUSPENDED = 7;</code>
       */
      public static final int SUSPENDED_VALUE = 7;
      /**
       * <code>DISCONNECTING = 8;</code>
       */
      public static final int DISCONNECTING_VALUE = 8;
      /**
       * <code>DISCONNECTED = 9;</code>
       */
      public static final int DISCONNECTED_VALUE = 9;
      /**
       * <code>FAILED = 10;</code>
       */
      public static final int FAILED_VALUE = 10;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NetState valueOf(int value) {
        return forNumber(value);
      }

      public static NetState forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return IDLE;
          case 2: return SCANNING;
          case 3: return CONNECTING;
          case 4: return AUTHENTICATING;
          case 5: return OBTAINING_IPADDR;
          case 6: return CONNECTED;
          case 7: return SUSPENDED;
          case 8: return DISCONNECTING;
          case 9: return DISCONNECTED;
          case 10: return FAILED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NetState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetState>() {
              public NetState findValueByNumber(int number) {
                return NetState.forNumber(number);
              }
            };

      private final int value;

      private NetState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntry.NetState)
    }

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html#getDataActivity() 
     * </pre>
     *
     * Protobuf enum {@code DataEntry.DataActivity}
     */
    public enum DataActivity
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>DATA_ACTIVITY_NONE = 0;</code>
       */
      DATA_ACTIVITY_NONE(0),
      /**
       * <code>DATA_ACTIVITY_IN = 1;</code>
       */
      DATA_ACTIVITY_IN(1),
      /**
       * <code>DATA_ACTIVITY_OUT = 2;</code>
       */
      DATA_ACTIVITY_OUT(2),
      /**
       * <code>DATA_ACTIVITY_INOUT = 3;</code>
       */
      DATA_ACTIVITY_INOUT(3),
      /**
       * <code>DATA_ACTIVITY_DORMANT = 4;</code>
       */
      DATA_ACTIVITY_DORMANT(4),
      /**
       * <code>DATA_ACTIVITY_UNKNOWN = 5;</code>
       */
      DATA_ACTIVITY_UNKNOWN(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DATA_ACTIVITY_NONE = 0;</code>
       */
      public static final int DATA_ACTIVITY_NONE_VALUE = 0;
      /**
       * <code>DATA_ACTIVITY_IN = 1;</code>
       */
      public static final int DATA_ACTIVITY_IN_VALUE = 1;
      /**
       * <code>DATA_ACTIVITY_OUT = 2;</code>
       */
      public static final int DATA_ACTIVITY_OUT_VALUE = 2;
      /**
       * <code>DATA_ACTIVITY_INOUT = 3;</code>
       */
      public static final int DATA_ACTIVITY_INOUT_VALUE = 3;
      /**
       * <code>DATA_ACTIVITY_DORMANT = 4;</code>
       */
      public static final int DATA_ACTIVITY_DORMANT_VALUE = 4;
      /**
       * <code>DATA_ACTIVITY_UNKNOWN = 5;</code>
       */
      public static final int DATA_ACTIVITY_UNKNOWN_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataActivity valueOf(int value) {
        return forNumber(value);
      }

      public static DataActivity forNumber(int value) {
        switch (value) {
          case 0: return DATA_ACTIVITY_NONE;
          case 1: return DATA_ACTIVITY_IN;
          case 2: return DATA_ACTIVITY_OUT;
          case 3: return DATA_ACTIVITY_INOUT;
          case 4: return DATA_ACTIVITY_DORMANT;
          case 5: return DATA_ACTIVITY_UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataActivity>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataActivity> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataActivity>() {
              public DataActivity findValueByNumber(int number) {
                return DataActivity.forNumber(number);
              }
            };

      private final int value;

      private DataActivity(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntry.DataActivity)
    }

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * Protobuf enum {@code DataEntry.VoiceCallActivity}
     */
    public enum VoiceCallActivity
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>CALL_STATE_IDLE = 0;</code>
       */
      CALL_STATE_IDLE(0),
      /**
       * <code>CALL_STATE_RINGING = 1;</code>
       */
      CALL_STATE_RINGING(1),
      /**
       * <code>CALL_STATE_OFFHOOK = 2;</code>
       */
      CALL_STATE_OFFHOOK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CALL_STATE_IDLE = 0;</code>
       */
      public static final int CALL_STATE_IDLE_VALUE = 0;
      /**
       * <code>CALL_STATE_RINGING = 1;</code>
       */
      public static final int CALL_STATE_RINGING_VALUE = 1;
      /**
       * <code>CALL_STATE_OFFHOOK = 2;</code>
       */
      public static final int CALL_STATE_OFFHOOK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VoiceCallActivity valueOf(int value) {
        return forNumber(value);
      }

      public static VoiceCallActivity forNumber(int value) {
        switch (value) {
          case 0: return CALL_STATE_IDLE;
          case 1: return CALL_STATE_RINGING;
          case 2: return CALL_STATE_OFFHOOK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<VoiceCallActivity>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          VoiceCallActivity> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<VoiceCallActivity>() {
              public VoiceCallActivity findValueByNumber(int number) {
                return VoiceCallActivity.forNumber(number);
              }
            };

      private final int value;

      private VoiceCallActivity(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntry.VoiceCallActivity)
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long tIMESTAMP_;
    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    public long getTIMESTAMP() {
      return tIMESTAMP_;
    }
    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    private void setTIMESTAMP(long value) {
      
      tIMESTAMP_ = value;
    }
    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    private void clearTIMESTAMP() {
      
      tIMESTAMP_ = 0L;
    }

    public static final int FUSED_LAT_FIELD_NUMBER = 2;
    private double fUSEDLAT_;
    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    public double getFUSEDLAT() {
      return fUSEDLAT_;
    }
    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    private void setFUSEDLAT(double value) {
      
      fUSEDLAT_ = value;
    }
    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    private void clearFUSEDLAT() {
      
      fUSEDLAT_ = 0D;
    }

    public static final int FUSED_LONG_FIELD_NUMBER = 3;
    private double fUSEDLONG_;
    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    public double getFUSEDLONG() {
      return fUSEDLONG_;
    }
    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    private void setFUSEDLONG(double value) {
      
      fUSEDLONG_ = value;
    }
    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    private void clearFUSEDLONG() {
      
      fUSEDLONG_ = 0D;
    }

    public static final int STALE_FIELD_NUMBER = 4;
    private boolean sTALE_;
    /**
     * <code>optional bool STALE = 4;</code>
     */
    public boolean getSTALE() {
      return sTALE_;
    }
    /**
     * <code>optional bool STALE = 4;</code>
     */
    private void setSTALE(boolean value) {
      
      sTALE_ = value;
    }
    /**
     * <code>optional bool STALE = 4;</code>
     */
    private void clearSTALE() {
      
      sTALE_ = false;
    }

    public static final int NETWORK_TYPE_FIELD_NUMBER = 5;
    private int nETWORKTYPE_;
    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    public int getNETWORKTYPEValue() {
      return nETWORKTYPE_;
    }
    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType getNETWORKTYPE() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType result = edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType.forNumber(nETWORKTYPE_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    private void setNETWORKTYPEValue(int value) {
        nETWORKTYPE_ = value;
    }
    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    private void setNETWORKTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nETWORKTYPE_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
     */
    private void clearNETWORKTYPE() {
      
      nETWORKTYPE_ = 0;
    }

    public static final int NETWORK_CELL_TYPE_FIELD_NUMBER = 6;
    private int nETWORKCELLTYPE_;
    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    public int getNETWORKCELLTYPEValue() {
      return nETWORKCELLTYPE_;
    }
    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType getNETWORKCELLTYPE() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType result = edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType.forNumber(nETWORKCELLTYPE_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    private void setNETWORKCELLTYPEValue(int value) {
        nETWORKCELLTYPE_ = value;
    }
    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    private void setNETWORKCELLTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nETWORKCELLTYPE_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
     */
    private void clearNETWORKCELLTYPE() {
      
      nETWORKCELLTYPE_ = 0;
    }

    public static final int NETWORK_PARAM_1_FIELD_NUMBER = 7;
    private int nETWORKPARAM1_;
    /**
     * <pre>
     * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
     * </pre>
     *
     * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
     */
    public int getNETWORKPARAM1() {
      return nETWORKPARAM1_;
    }
    /**
     * <pre>
     * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
     * </pre>
     *
     * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
     */
    private void setNETWORKPARAM1(int value) {
      
      nETWORKPARAM1_ = value;
    }
    /**
     * <pre>
     * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
     * </pre>
     *
     * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
     */
    private void clearNETWORKPARAM1() {
      
      nETWORKPARAM1_ = 0;
    }

    public static final int NETWORK_PARAM_2_FIELD_NUMBER = 8;
    private int nETWORKPARAM2_;
    /**
     * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
     */
    public int getNETWORKPARAM2() {
      return nETWORKPARAM2_;
    }
    /**
     * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
     */
    private void setNETWORKPARAM2(int value) {
      
      nETWORKPARAM2_ = value;
    }
    /**
     * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
     */
    private void clearNETWORKPARAM2() {
      
      nETWORKPARAM2_ = 0;
    }

    public static final int NETWORK_PARAM_3_FIELD_NUMBER = 9;
    private int nETWORKPARAM3_;
    /**
     * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
     */
    public int getNETWORKPARAM3() {
      return nETWORKPARAM3_;
    }
    /**
     * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
     */
    private void setNETWORKPARAM3(int value) {
      
      nETWORKPARAM3_ = value;
    }
    /**
     * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
     */
    private void clearNETWORKPARAM3() {
      
      nETWORKPARAM3_ = 0;
    }

    public static final int NETWORK_PARAM_4_FIELD_NUMBER = 10;
    private int nETWORKPARAM4_;
    /**
     * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
     */
    public int getNETWORKPARAM4() {
      return nETWORKPARAM4_;
    }
    /**
     * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
     */
    private void setNETWORKPARAM4(int value) {
      
      nETWORKPARAM4_ = value;
    }
    /**
     * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
     */
    private void clearNETWORKPARAM4() {
      
      nETWORKPARAM4_ = 0;
    }

    public static final int SIGNAL_ASU_LEVEL_FIELD_NUMBER = 11;
    private int sIGNALASULEVEL_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
     * </pre>
     *
     * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
     */
    public int getSIGNALASULEVEL() {
      return sIGNALASULEVEL_;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
     * </pre>
     *
     * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
     */
    private void setSIGNALASULEVEL(int value) {
      
      sIGNALASULEVEL_ = value;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
     * </pre>
     *
     * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
     */
    private void clearSIGNALASULEVEL() {
      
      sIGNALASULEVEL_ = 0;
    }

    public static final int SIGNAL_DBM_FIELD_NUMBER = 12;
    private int sIGNALDBM_;
    /**
     * <code>optional sint32 SIGNAL_DBM = 12;</code>
     */
    public int getSIGNALDBM() {
      return sIGNALDBM_;
    }
    /**
     * <code>optional sint32 SIGNAL_DBM = 12;</code>
     */
    private void setSIGNALDBM(int value) {
      
      sIGNALDBM_ = value;
    }
    /**
     * <code>optional sint32 SIGNAL_DBM = 12;</code>
     */
    private void clearSIGNALDBM() {
      
      sIGNALDBM_ = 0;
    }

    public static final int SIGNAL_LEVEL_FIELD_NUMBER = 13;
    private int sIGNALLEVEL_;
    /**
     * <code>optional int32 SIGNAL_LEVEL = 13;</code>
     */
    public int getSIGNALLEVEL() {
      return sIGNALLEVEL_;
    }
    /**
     * <code>optional int32 SIGNAL_LEVEL = 13;</code>
     */
    private void setSIGNALLEVEL(int value) {
      
      sIGNALLEVEL_ = value;
    }
    /**
     * <code>optional int32 SIGNAL_LEVEL = 13;</code>
     */
    private void clearSIGNALLEVEL() {
      
      sIGNALLEVEL_ = 0;
    }

    public static final int NETWORK_STATE_FIELD_NUMBER = 14;
    private int nETWORKSTATE_;
    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    public int getNETWORKSTATEValue() {
      return nETWORKSTATE_;
    }
    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState getNETWORKSTATE() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState result = edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState.forNumber(nETWORKSTATE_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    private void setNETWORKSTATEValue(int value) {
        nETWORKSTATE_ = value;
    }
    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    private void setNETWORKSTATE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nETWORKSTATE_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
     */
    private void clearNETWORKSTATE() {
      
      nETWORKSTATE_ = 0;
    }

    public static final int NETWORK_DATA_ACTIVITY_FIELD_NUMBER = 15;
    private int nETWORKDATAACTIVITY_;
    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    public int getNETWORKDATAACTIVITYValue() {
      return nETWORKDATAACTIVITY_;
    }
    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity getNETWORKDATAACTIVITY() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity result = edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity.forNumber(nETWORKDATAACTIVITY_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    private void setNETWORKDATAACTIVITYValue(int value) {
        nETWORKDATAACTIVITY_ = value;
    }
    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    private void setNETWORKDATAACTIVITY(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nETWORKDATAACTIVITY_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
     */
    private void clearNETWORKDATAACTIVITY() {
      
      nETWORKDATAACTIVITY_ = 0;
    }

    public static final int VOICE_CALL_STATE_FIELD_NUMBER = 16;
    private int vOICECALLSTATE_;
    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    public int getVOICECALLSTATEValue() {
      return vOICECALLSTATE_;
    }
    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity getVOICECALLSTATE() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity result = edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity.forNumber(vOICECALLSTATE_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    private void setVOICECALLSTATEValue(int value) {
        vOICECALLSTATE_ = value;
    }
    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    private void setVOICECALLSTATE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      vOICECALLSTATE_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
     */
    private void clearVOICECALLSTATE() {
      
      vOICECALLSTATE_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tIMESTAMP_ != 0L) {
        output.writeUInt64(1, tIMESTAMP_);
      }
      if (fUSEDLAT_ != 0D) {
        output.writeDouble(2, fUSEDLAT_);
      }
      if (fUSEDLONG_ != 0D) {
        output.writeDouble(3, fUSEDLONG_);
      }
      if (sTALE_ != false) {
        output.writeBool(4, sTALE_);
      }
      if (nETWORKTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType.NETWORK_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(5, nETWORKTYPE_);
      }
      if (nETWORKCELLTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType.GSM.getNumber()) {
        output.writeEnum(6, nETWORKCELLTYPE_);
      }
      if (nETWORKPARAM1_ != 0) {
        output.writeInt32(7, nETWORKPARAM1_);
      }
      if (nETWORKPARAM2_ != 0) {
        output.writeInt32(8, nETWORKPARAM2_);
      }
      if (nETWORKPARAM3_ != 0) {
        output.writeInt32(9, nETWORKPARAM3_);
      }
      if (nETWORKPARAM4_ != 0) {
        output.writeInt32(10, nETWORKPARAM4_);
      }
      if (sIGNALASULEVEL_ != 0) {
        output.writeInt32(11, sIGNALASULEVEL_);
      }
      if (sIGNALDBM_ != 0) {
        output.writeSInt32(12, sIGNALDBM_);
      }
      if (sIGNALLEVEL_ != 0) {
        output.writeInt32(13, sIGNALLEVEL_);
      }
      if (nETWORKSTATE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState.UNKNOWN.getNumber()) {
        output.writeEnum(14, nETWORKSTATE_);
      }
      if (nETWORKDATAACTIVITY_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity.DATA_ACTIVITY_NONE.getNumber()) {
        output.writeEnum(15, nETWORKDATAACTIVITY_);
      }
      if (vOICECALLSTATE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity.CALL_STATE_IDLE.getNumber()) {
        output.writeEnum(16, vOICECALLSTATE_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (tIMESTAMP_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, tIMESTAMP_);
      }
      if (fUSEDLAT_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, fUSEDLAT_);
      }
      if (fUSEDLONG_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, fUSEDLONG_);
      }
      if (sTALE_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, sTALE_);
      }
      if (nETWORKTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType.NETWORK_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, nETWORKTYPE_);
      }
      if (nETWORKCELLTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType.GSM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, nETWORKCELLTYPE_);
      }
      if (nETWORKPARAM1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, nETWORKPARAM1_);
      }
      if (nETWORKPARAM2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, nETWORKPARAM2_);
      }
      if (nETWORKPARAM3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, nETWORKPARAM3_);
      }
      if (nETWORKPARAM4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, nETWORKPARAM4_);
      }
      if (sIGNALASULEVEL_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, sIGNALASULEVEL_);
      }
      if (sIGNALDBM_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(12, sIGNALDBM_);
      }
      if (sIGNALLEVEL_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, sIGNALLEVEL_);
      }
      if (nETWORKSTATE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(14, nETWORKSTATE_);
      }
      if (nETWORKDATAACTIVITY_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity.DATA_ACTIVITY_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(15, nETWORKDATAACTIVITY_);
      }
      if (vOICECALLSTATE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity.CALL_STATE_IDLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(16, vOICECALLSTATE_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code DataEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry, Builder> implements
        // @@protoc_insertion_point(builder_implements:DataEntry)
        edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntryOrBuilder {
      // Construct using edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Timestamp 
       * </pre>
       *
       * <code>optional uint64 TIMESTAMP = 1;</code>
       */
      public long getTIMESTAMP() {
        return instance.getTIMESTAMP();
      }
      /**
       * <pre>
       * Timestamp 
       * </pre>
       *
       * <code>optional uint64 TIMESTAMP = 1;</code>
       */
      public Builder setTIMESTAMP(long value) {
        copyOnWrite();
        instance.setTIMESTAMP(value);
        return this;
      }
      /**
       * <pre>
       * Timestamp 
       * </pre>
       *
       * <code>optional uint64 TIMESTAMP = 1;</code>
       */
      public Builder clearTIMESTAMP() {
        copyOnWrite();
        instance.clearTIMESTAMP();
        return this;
      }

      /**
       * <pre>
       * Location 
       * </pre>
       *
       * <code>optional double FUSED_LAT = 2;</code>
       */
      public double getFUSEDLAT() {
        return instance.getFUSEDLAT();
      }
      /**
       * <pre>
       * Location 
       * </pre>
       *
       * <code>optional double FUSED_LAT = 2;</code>
       */
      public Builder setFUSEDLAT(double value) {
        copyOnWrite();
        instance.setFUSEDLAT(value);
        return this;
      }
      /**
       * <pre>
       * Location 
       * </pre>
       *
       * <code>optional double FUSED_LAT = 2;</code>
       */
      public Builder clearFUSEDLAT() {
        copyOnWrite();
        instance.clearFUSEDLAT();
        return this;
      }

      /**
       * <code>optional double FUSED_LONG = 3;</code>
       */
      public double getFUSEDLONG() {
        return instance.getFUSEDLONG();
      }
      /**
       * <code>optional double FUSED_LONG = 3;</code>
       */
      public Builder setFUSEDLONG(double value) {
        copyOnWrite();
        instance.setFUSEDLONG(value);
        return this;
      }
      /**
       * <code>optional double FUSED_LONG = 3;</code>
       */
      public Builder clearFUSEDLONG() {
        copyOnWrite();
        instance.clearFUSEDLONG();
        return this;
      }

      /**
       * <code>optional bool STALE = 4;</code>
       */
      public boolean getSTALE() {
        return instance.getSTALE();
      }
      /**
       * <code>optional bool STALE = 4;</code>
       */
      public Builder setSTALE(boolean value) {
        copyOnWrite();
        instance.setSTALE(value);
        return this;
      }
      /**
       * <code>optional bool STALE = 4;</code>
       */
      public Builder clearSTALE() {
        copyOnWrite();
        instance.clearSTALE();
        return this;
      }

      /**
       * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
       */
      public int getNETWORKTYPEValue() {
        return instance.getNETWORKTYPEValue();
      }
      /**
       * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
       */
      public Builder setNETWORKTYPEValue(int value) {
        copyOnWrite();
        instance.setNETWORKTYPEValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType getNETWORKTYPE() {
        return instance.getNETWORKTYPE();
      }
      /**
       * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
       */
      public Builder setNETWORKTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetType value) {
        copyOnWrite();
        instance.setNETWORKTYPE(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.NetType NETWORK_TYPE = 5;</code>
       */
      public Builder clearNETWORKTYPE() {
        copyOnWrite();
        instance.clearNETWORKTYPE();
        return this;
      }

      /**
       * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
       */
      public int getNETWORKCELLTYPEValue() {
        return instance.getNETWORKCELLTYPEValue();
      }
      /**
       * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
       */
      public Builder setNETWORKCELLTYPEValue(int value) {
        copyOnWrite();
        instance.setNETWORKCELLTYPEValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType getNETWORKCELLTYPE() {
        return instance.getNETWORKCELLTYPE();
      }
      /**
       * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
       */
      public Builder setNETWORKCELLTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.CellType value) {
        copyOnWrite();
        instance.setNETWORKCELLTYPE(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.CellType NETWORK_CELL_TYPE = 6;</code>
       */
      public Builder clearNETWORKCELLTYPE() {
        copyOnWrite();
        instance.clearNETWORKCELLTYPE();
        return this;
      }

      /**
       * <pre>
       * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
       * </pre>
       *
       * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
       */
      public int getNETWORKPARAM1() {
        return instance.getNETWORKPARAM1();
      }
      /**
       * <pre>
       * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
       * </pre>
       *
       * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
       */
      public Builder setNETWORKPARAM1(int value) {
        copyOnWrite();
        instance.setNETWORKPARAM1(value);
        return this;
      }
      /**
       * <pre>
       * Network Parameters: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
       * </pre>
       *
       * <code>optional int32 NETWORK_PARAM_1 = 7;</code>
       */
      public Builder clearNETWORKPARAM1() {
        copyOnWrite();
        instance.clearNETWORKPARAM1();
        return this;
      }

      /**
       * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
       */
      public int getNETWORKPARAM2() {
        return instance.getNETWORKPARAM2();
      }
      /**
       * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
       */
      public Builder setNETWORKPARAM2(int value) {
        copyOnWrite();
        instance.setNETWORKPARAM2(value);
        return this;
      }
      /**
       * <code>optional int32 NETWORK_PARAM_2 = 8;</code>
       */
      public Builder clearNETWORKPARAM2() {
        copyOnWrite();
        instance.clearNETWORKPARAM2();
        return this;
      }

      /**
       * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
       */
      public int getNETWORKPARAM3() {
        return instance.getNETWORKPARAM3();
      }
      /**
       * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
       */
      public Builder setNETWORKPARAM3(int value) {
        copyOnWrite();
        instance.setNETWORKPARAM3(value);
        return this;
      }
      /**
       * <code>optional int32 NETWORK_PARAM_3 = 9;</code>
       */
      public Builder clearNETWORKPARAM3() {
        copyOnWrite();
        instance.clearNETWORKPARAM3();
        return this;
      }

      /**
       * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
       */
      public int getNETWORKPARAM4() {
        return instance.getNETWORKPARAM4();
      }
      /**
       * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
       */
      public Builder setNETWORKPARAM4(int value) {
        copyOnWrite();
        instance.setNETWORKPARAM4(value);
        return this;
      }
      /**
       * <code>optional int32 NETWORK_PARAM_4 = 10;</code>
       */
      public Builder clearNETWORKPARAM4() {
        copyOnWrite();
        instance.clearNETWORKPARAM4();
        return this;
      }

      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
       * </pre>
       *
       * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
       */
      public int getSIGNALASULEVEL() {
        return instance.getSIGNALASULEVEL();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
       * </pre>
       *
       * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
       */
      public Builder setSIGNALASULEVEL(int value) {
        copyOnWrite();
        instance.setSIGNALASULEVEL(value);
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/CellSignalStrength.html 
       * </pre>
       *
       * <code>optional int32 SIGNAL_ASU_LEVEL = 11;</code>
       */
      public Builder clearSIGNALASULEVEL() {
        copyOnWrite();
        instance.clearSIGNALASULEVEL();
        return this;
      }

      /**
       * <code>optional sint32 SIGNAL_DBM = 12;</code>
       */
      public int getSIGNALDBM() {
        return instance.getSIGNALDBM();
      }
      /**
       * <code>optional sint32 SIGNAL_DBM = 12;</code>
       */
      public Builder setSIGNALDBM(int value) {
        copyOnWrite();
        instance.setSIGNALDBM(value);
        return this;
      }
      /**
       * <code>optional sint32 SIGNAL_DBM = 12;</code>
       */
      public Builder clearSIGNALDBM() {
        copyOnWrite();
        instance.clearSIGNALDBM();
        return this;
      }

      /**
       * <code>optional int32 SIGNAL_LEVEL = 13;</code>
       */
      public int getSIGNALLEVEL() {
        return instance.getSIGNALLEVEL();
      }
      /**
       * <code>optional int32 SIGNAL_LEVEL = 13;</code>
       */
      public Builder setSIGNALLEVEL(int value) {
        copyOnWrite();
        instance.setSIGNALLEVEL(value);
        return this;
      }
      /**
       * <code>optional int32 SIGNAL_LEVEL = 13;</code>
       */
      public Builder clearSIGNALLEVEL() {
        copyOnWrite();
        instance.clearSIGNALLEVEL();
        return this;
      }

      /**
       * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
       */
      public int getNETWORKSTATEValue() {
        return instance.getNETWORKSTATEValue();
      }
      /**
       * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
       */
      public Builder setNETWORKSTATEValue(int value) {
        copyOnWrite();
        instance.setNETWORKSTATEValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState getNETWORKSTATE() {
        return instance.getNETWORKSTATE();
      }
      /**
       * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
       */
      public Builder setNETWORKSTATE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.NetState value) {
        copyOnWrite();
        instance.setNETWORKSTATE(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.NetState NETWORK_STATE = 14;</code>
       */
      public Builder clearNETWORKSTATE() {
        copyOnWrite();
        instance.clearNETWORKSTATE();
        return this;
      }

      /**
       * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
       */
      public int getNETWORKDATAACTIVITYValue() {
        return instance.getNETWORKDATAACTIVITYValue();
      }
      /**
       * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
       */
      public Builder setNETWORKDATAACTIVITYValue(int value) {
        copyOnWrite();
        instance.setNETWORKDATAACTIVITYValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity getNETWORKDATAACTIVITY() {
        return instance.getNETWORKDATAACTIVITY();
      }
      /**
       * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
       */
      public Builder setNETWORKDATAACTIVITY(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.DataActivity value) {
        copyOnWrite();
        instance.setNETWORKDATAACTIVITY(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.DataActivity NETWORK_DATA_ACTIVITY = 15;</code>
       */
      public Builder clearNETWORKDATAACTIVITY() {
        copyOnWrite();
        instance.clearNETWORKDATAACTIVITY();
        return this;
      }

      /**
       * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
       */
      public int getVOICECALLSTATEValue() {
        return instance.getVOICECALLSTATEValue();
      }
      /**
       * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
       */
      public Builder setVOICECALLSTATEValue(int value) {
        copyOnWrite();
        instance.setVOICECALLSTATEValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity getVOICECALLSTATE() {
        return instance.getVOICECALLSTATE();
      }
      /**
       * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
       */
      public Builder setVOICECALLSTATE(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.VoiceCallActivity value) {
        copyOnWrite();
        instance.setVOICECALLSTATE(value);
        return this;
      }
      /**
       * <code>optional .DataEntry.VoiceCallActivity VOICE_CALL_STATE = 16;</code>
       */
      public Builder clearVOICECALLSTATE() {
        copyOnWrite();
        instance.clearVOICECALLSTATE();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DataEntry)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry other = (edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry) arg1;
          tIMESTAMP_ = visitor.visitLong(tIMESTAMP_ != 0L, tIMESTAMP_,
              other.tIMESTAMP_ != 0L, other.tIMESTAMP_);
          fUSEDLAT_ = visitor.visitDouble(fUSEDLAT_ != 0D, fUSEDLAT_,
              other.fUSEDLAT_ != 0D, other.fUSEDLAT_);
          fUSEDLONG_ = visitor.visitDouble(fUSEDLONG_ != 0D, fUSEDLONG_,
              other.fUSEDLONG_ != 0D, other.fUSEDLONG_);
          sTALE_ = visitor.visitBoolean(sTALE_ != false, sTALE_,
              other.sTALE_ != false, other.sTALE_);
          nETWORKTYPE_ = visitor.visitInt(nETWORKTYPE_ != 0, nETWORKTYPE_,    other.nETWORKTYPE_ != 0, other.nETWORKTYPE_);
          nETWORKCELLTYPE_ = visitor.visitInt(nETWORKCELLTYPE_ != 0, nETWORKCELLTYPE_,    other.nETWORKCELLTYPE_ != 0, other.nETWORKCELLTYPE_);
          nETWORKPARAM1_ = visitor.visitInt(nETWORKPARAM1_ != 0, nETWORKPARAM1_,
              other.nETWORKPARAM1_ != 0, other.nETWORKPARAM1_);
          nETWORKPARAM2_ = visitor.visitInt(nETWORKPARAM2_ != 0, nETWORKPARAM2_,
              other.nETWORKPARAM2_ != 0, other.nETWORKPARAM2_);
          nETWORKPARAM3_ = visitor.visitInt(nETWORKPARAM3_ != 0, nETWORKPARAM3_,
              other.nETWORKPARAM3_ != 0, other.nETWORKPARAM3_);
          nETWORKPARAM4_ = visitor.visitInt(nETWORKPARAM4_ != 0, nETWORKPARAM4_,
              other.nETWORKPARAM4_ != 0, other.nETWORKPARAM4_);
          sIGNALASULEVEL_ = visitor.visitInt(sIGNALASULEVEL_ != 0, sIGNALASULEVEL_,
              other.sIGNALASULEVEL_ != 0, other.sIGNALASULEVEL_);
          sIGNALDBM_ = visitor.visitInt(sIGNALDBM_ != 0, sIGNALDBM_,
              other.sIGNALDBM_ != 0, other.sIGNALDBM_);
          sIGNALLEVEL_ = visitor.visitInt(sIGNALLEVEL_ != 0, sIGNALLEVEL_,
              other.sIGNALLEVEL_ != 0, other.sIGNALLEVEL_);
          nETWORKSTATE_ = visitor.visitInt(nETWORKSTATE_ != 0, nETWORKSTATE_,    other.nETWORKSTATE_ != 0, other.nETWORKSTATE_);
          nETWORKDATAACTIVITY_ = visitor.visitInt(nETWORKDATAACTIVITY_ != 0, nETWORKDATAACTIVITY_,    other.nETWORKDATAACTIVITY_ != 0, other.nETWORKDATAACTIVITY_);
          vOICECALLSTATE_ = visitor.visitInt(vOICECALLSTATE_ != 0, vOICECALLSTATE_,    other.vOICECALLSTATE_ != 0, other.vOICECALLSTATE_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  tIMESTAMP_ = input.readUInt64();
                  break;
                }
                case 17: {

                  fUSEDLAT_ = input.readDouble();
                  break;
                }
                case 25: {

                  fUSEDLONG_ = input.readDouble();
                  break;
                }
                case 32: {

                  sTALE_ = input.readBool();
                  break;
                }
                case 40: {
                  int rawValue = input.readEnum();

                  nETWORKTYPE_ = rawValue;
                  break;
                }
                case 48: {
                  int rawValue = input.readEnum();

                  nETWORKCELLTYPE_ = rawValue;
                  break;
                }
                case 56: {

                  nETWORKPARAM1_ = input.readInt32();
                  break;
                }
                case 64: {

                  nETWORKPARAM2_ = input.readInt32();
                  break;
                }
                case 72: {

                  nETWORKPARAM3_ = input.readInt32();
                  break;
                }
                case 80: {

                  nETWORKPARAM4_ = input.readInt32();
                  break;
                }
                case 88: {

                  sIGNALASULEVEL_ = input.readInt32();
                  break;
                }
                case 96: {

                  sIGNALDBM_ = input.readSInt32();
                  break;
                }
                case 104: {

                  sIGNALLEVEL_ = input.readInt32();
                  break;
                }
                case 112: {
                  int rawValue = input.readEnum();

                  nETWORKSTATE_ = rawValue;
                  break;
                }
                case 120: {
                  int rawValue = input.readEnum();

                  nETWORKDATAACTIVITY_ = rawValue;
                  break;
                }
                case 128: {
                  int rawValue = input.readEnum();

                  vOICECALLSTATE_ = rawValue;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:DataEntry)
    private static final edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataEntry();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DataEntry> PARSER;

    public static com.google.protobuf.Parser<DataEntry> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataRecord)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    java.lang.String getIMEIHASH();
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    com.google.protobuf.ByteString
        getIMEIHASHBytes();

    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    java.lang.String getNETWORKOPERATORCODE();
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKOPERATORCODEBytes();

    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    java.lang.String getNETWORKOPERATORNAME();
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKOPERATORNAMEBytes();

    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    java.util.List<edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry> 
        getENTRYList();
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry getENTRY(int index);
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    int getENTRYCount();
  }
  /**
   * Protobuf type {@code DataRecord}
   */
  public  static final class DataRecord extends
      com.google.protobuf.GeneratedMessageLite<
          DataRecord, DataRecord.Builder> implements
      // @@protoc_insertion_point(message_implements:DataRecord)
      DataRecordOrBuilder {
    private DataRecord() {
      iMEIHASH_ = "";
      nETWORKOPERATORCODE_ = "";
      nETWORKOPERATORNAME_ = "";
      eNTRY_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int IMEI_HASH_FIELD_NUMBER = 1;
    private java.lang.String iMEIHASH_;
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public java.lang.String getIMEIHASH() {
      return iMEIHASH_;
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIMEIHASHBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(iMEIHASH_);
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void setIMEIHASH(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iMEIHASH_ = value;
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void clearIMEIHASH() {
      
      iMEIHASH_ = getDefaultInstance().getIMEIHASH();
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void setIMEIHASHBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iMEIHASH_ = value.toStringUtf8();
    }

    public static final int NETWORK_OPERATOR_CODE_FIELD_NUMBER = 2;
    private java.lang.String nETWORKOPERATORCODE_;
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    public java.lang.String getNETWORKOPERATORCODE() {
      return nETWORKOPERATORCODE_;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKOPERATORCODEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nETWORKOPERATORCODE_);
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    private void setNETWORKOPERATORCODE(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nETWORKOPERATORCODE_ = value;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    private void clearNETWORKOPERATORCODE() {
      
      nETWORKOPERATORCODE_ = getDefaultInstance().getNETWORKOPERATORCODE();
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
     */
    private void setNETWORKOPERATORCODEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nETWORKOPERATORCODE_ = value.toStringUtf8();
    }

    public static final int NETWORK_OPERATOR_NAME_FIELD_NUMBER = 3;
    private java.lang.String nETWORKOPERATORNAME_;
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    public java.lang.String getNETWORKOPERATORNAME() {
      return nETWORKOPERATORNAME_;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKOPERATORNAMEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nETWORKOPERATORNAME_);
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    private void setNETWORKOPERATORNAME(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nETWORKOPERATORNAME_ = value;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    private void clearNETWORKOPERATORNAME() {
      
      nETWORKOPERATORNAME_ = getDefaultInstance().getNETWORKOPERATORNAME();
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
     */
    private void setNETWORKOPERATORNAMEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nETWORKOPERATORNAME_ = value.toStringUtf8();
    }

    public static final int ENTRY_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry> eNTRY_;
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    public java.util.List<edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry> getENTRYList() {
      return eNTRY_;
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    public java.util.List<? extends edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntryOrBuilder> 
        getENTRYOrBuilderList() {
      return eNTRY_;
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    public int getENTRYCount() {
      return eNTRY_.size();
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry getENTRY(int index) {
      return eNTRY_.get(index);
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntryOrBuilder getENTRYOrBuilder(
        int index) {
      return eNTRY_.get(index);
    }
    private void ensureENTRYIsMutable() {
      if (!eNTRY_.isModifiable()) {
        eNTRY_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(eNTRY_);
       }
    }

    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void setENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureENTRYIsMutable();
      eNTRY_.set(index, value);
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void setENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.Builder builderForValue) {
      ensureENTRYIsMutable();
      eNTRY_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void addENTRY(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureENTRYIsMutable();
      eNTRY_.add(value);
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void addENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureENTRYIsMutable();
      eNTRY_.add(index, value);
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void addENTRY(
        edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.Builder builderForValue) {
      ensureENTRYIsMutable();
      eNTRY_.add(builderForValue.build());
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void addENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.Builder builderForValue) {
      ensureENTRYIsMutable();
      eNTRY_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void addAllENTRY(
        java.lang.Iterable<? extends edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry> values) {
      ensureENTRYIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, eNTRY_);
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void clearENTRY() {
      eNTRY_ = emptyProtobufList();
    }
    /**
     * <code>repeated .DataEntry ENTRY = 4;</code>
     */
    private void removeENTRY(int index) {
      ensureENTRYIsMutable();
      eNTRY_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!iMEIHASH_.isEmpty()) {
        output.writeString(1, getIMEIHASH());
      }
      if (!nETWORKOPERATORCODE_.isEmpty()) {
        output.writeString(2, getNETWORKOPERATORCODE());
      }
      if (!nETWORKOPERATORNAME_.isEmpty()) {
        output.writeString(3, getNETWORKOPERATORNAME());
      }
      for (int i = 0; i < eNTRY_.size(); i++) {
        output.writeMessage(4, eNTRY_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!iMEIHASH_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIMEIHASH());
      }
      if (!nETWORKOPERATORCODE_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNETWORKOPERATORCODE());
      }
      if (!nETWORKOPERATORNAME_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNETWORKOPERATORNAME());
      }
      for (int i = 0; i < eNTRY_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, eNTRY_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code DataRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord, Builder> implements
        // @@protoc_insertion_point(builder_implements:DataRecord)
        edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecordOrBuilder {
      // Construct using edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public java.lang.String getIMEIHASH() {
        return instance.getIMEIHASH();
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIMEIHASHBytes() {
        return instance.getIMEIHASHBytes();
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASH(
          java.lang.String value) {
        copyOnWrite();
        instance.setIMEIHASH(value);
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder clearIMEIHASH() {
        copyOnWrite();
        instance.clearIMEIHASH();
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASHBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIMEIHASHBytes(value);
        return this;
      }

      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
       */
      public java.lang.String getNETWORKOPERATORCODE() {
        return instance.getNETWORKOPERATORCODE();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKOPERATORCODEBytes() {
        return instance.getNETWORKOPERATORCODEBytes();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
       */
      public Builder setNETWORKOPERATORCODE(
          java.lang.String value) {
        copyOnWrite();
        instance.setNETWORKOPERATORCODE(value);
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
       */
      public Builder clearNETWORKOPERATORCODE() {
        copyOnWrite();
        instance.clearNETWORKOPERATORCODE();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 2;</code>
       */
      public Builder setNETWORKOPERATORCODEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNETWORKOPERATORCODEBytes(value);
        return this;
      }

      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
       */
      public java.lang.String getNETWORKOPERATORNAME() {
        return instance.getNETWORKOPERATORNAME();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKOPERATORNAMEBytes() {
        return instance.getNETWORKOPERATORNAMEBytes();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
       */
      public Builder setNETWORKOPERATORNAME(
          java.lang.String value) {
        copyOnWrite();
        instance.setNETWORKOPERATORNAME(value);
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
       */
      public Builder clearNETWORKOPERATORNAME() {
        copyOnWrite();
        instance.clearNETWORKOPERATORNAME();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 3;</code>
       */
      public Builder setNETWORKOPERATORNAMEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNETWORKOPERATORNAMEBytes(value);
        return this;
      }

      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public java.util.List<edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry> getENTRYList() {
        return java.util.Collections.unmodifiableList(
            instance.getENTRYList());
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public int getENTRYCount() {
        return instance.getENTRYCount();
      }/**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry getENTRY(int index) {
        return instance.getENTRY(index);
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder setENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry value) {
        copyOnWrite();
        instance.setENTRY(index, value);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder setENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.Builder builderForValue) {
        copyOnWrite();
        instance.setENTRY(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder addENTRY(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry value) {
        copyOnWrite();
        instance.addENTRY(value);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder addENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry value) {
        copyOnWrite();
        instance.addENTRY(index, value);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder addENTRY(
          edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.Builder builderForValue) {
        copyOnWrite();
        instance.addENTRY(builderForValue);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder addENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.Builder builderForValue) {
        copyOnWrite();
        instance.addENTRY(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder addAllENTRY(
          java.lang.Iterable<? extends edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry> values) {
        copyOnWrite();
        instance.addAllENTRY(values);
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder clearENTRY() {
        copyOnWrite();
        instance.clearENTRY();
        return this;
      }
      /**
       * <code>repeated .DataEntry ENTRY = 4;</code>
       */
      public Builder removeENTRY(int index) {
        copyOnWrite();
        instance.removeENTRY(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DataRecord)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          eNTRY_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord other = (edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord) arg1;
          iMEIHASH_ = visitor.visitString(!iMEIHASH_.isEmpty(), iMEIHASH_,
              !other.iMEIHASH_.isEmpty(), other.iMEIHASH_);
          nETWORKOPERATORCODE_ = visitor.visitString(!nETWORKOPERATORCODE_.isEmpty(), nETWORKOPERATORCODE_,
              !other.nETWORKOPERATORCODE_.isEmpty(), other.nETWORKOPERATORCODE_);
          nETWORKOPERATORNAME_ = visitor.visitString(!nETWORKOPERATORNAME_.isEmpty(), nETWORKOPERATORNAME_,
              !other.nETWORKOPERATORNAME_.isEmpty(), other.nETWORKOPERATORNAME_);
          eNTRY_= visitor.visitList(eNTRY_, other.eNTRY_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  iMEIHASH_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  nETWORKOPERATORCODE_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  nETWORKOPERATORNAME_ = s;
                  break;
                }
                case 34: {
                  if (!eNTRY_.isModifiable()) {
                    eNTRY_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(eNTRY_);
                  }
                  eNTRY_.add(
                      input.readMessage(edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataEntry.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:DataRecord)
    private static final edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataRecord();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordOuterClass.DataRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DataRecord> PARSER;

    public static com.google.protobuf.Parser<DataRecord> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
