// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register_device.proto

package edu.buffalo.cse.ubwins.cellmon;

public final class RegisterDeviceOuterClass {
  private RegisterDeviceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RegisterDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegisterDevice)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    java.lang.String getIMEIHASH();
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    com.google.protobuf.ByteString
        getIMEIHASHBytes();

    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    java.lang.String getBOARD();
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    com.google.protobuf.ByteString
        getBOARDBytes();

    /**
     * <code>optional string BRAND = 3;</code>
     */
    java.lang.String getBRAND();
    /**
     * <code>optional string BRAND = 3;</code>
     */
    com.google.protobuf.ByteString
        getBRANDBytes();

    /**
     * <code>optional string DEVICE = 4;</code>
     */
    java.lang.String getDEVICE();
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    com.google.protobuf.ByteString
        getDEVICEBytes();

    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    java.lang.String getHARDWARE();
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    com.google.protobuf.ByteString
        getHARDWAREBytes();

    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    java.lang.String getMANUFACTURER();
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    com.google.protobuf.ByteString
        getMANUFACTURERBytes();

    /**
     * <code>optional string MODEL = 7;</code>
     */
    java.lang.String getMODEL();
    /**
     * <code>optional string MODEL = 7;</code>
     */
    com.google.protobuf.ByteString
        getMODELBytes();

    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    java.lang.String getPRODUCT();
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    com.google.protobuf.ByteString
        getPRODUCTBytes();

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    java.lang.String getNETWORKCOUNTRYISO();
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKCOUNTRYISOBytes();

    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    java.lang.String getNETWORKOPERATORCODE();
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKOPERATORCODEBytes();

    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    java.lang.String getNETWORKOPERATORNAME();
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    com.google.protobuf.ByteString
        getNETWORKOPERATORNAMEBytes();

    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    java.lang.String getPHONETYPE();
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    com.google.protobuf.ByteString
        getPHONETYPEBytes();

    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    java.lang.String getSIMCOUNTRYISO();
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    com.google.protobuf.ByteString
        getSIMCOUNTRYISOBytes();

    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    java.lang.String getSIMOPERATOR();
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    com.google.protobuf.ByteString
        getSIMOPERATORBytes();

    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    java.lang.String getSIMOPERATORNAME();
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    com.google.protobuf.ByteString
        getSIMOPERATORNAMEBytes();

    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    java.lang.String getRELEASE();
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    com.google.protobuf.ByteString
        getRELEASEBytes();

    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    java.lang.String getSDKINT();
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    com.google.protobuf.ByteString
        getSDKINTBytes();
  }
  /**
   * Protobuf type {@code RegisterDevice}
   */
  public  static final class RegisterDevice extends
      com.google.protobuf.GeneratedMessageLite<
          RegisterDevice, RegisterDevice.Builder> implements
      // @@protoc_insertion_point(message_implements:RegisterDevice)
      RegisterDeviceOrBuilder {
    private RegisterDevice() {
      iMEIHASH_ = "";
      bOARD_ = "";
      bRAND_ = "";
      dEVICE_ = "";
      hARDWARE_ = "";
      mANUFACTURER_ = "";
      mODEL_ = "";
      pRODUCT_ = "";
      nETWORKCOUNTRYISO_ = "";
      nETWORKOPERATORCODE_ = "";
      nETWORKOPERATORNAME_ = "";
      pHONETYPE_ = "";
      sIMCOUNTRYISO_ = "";
      sIMOPERATOR_ = "";
      sIMOPERATORNAME_ = "";
      rELEASE_ = "";
      sDKINT_ = "";
    }
    public static final int IMEI_HASH_FIELD_NUMBER = 1;
    private java.lang.String iMEIHASH_;
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public java.lang.String getIMEIHASH() {
      return iMEIHASH_;
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIMEIHASHBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(iMEIHASH_);
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void setIMEIHASH(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iMEIHASH_ = value;
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void clearIMEIHASH() {
      
      iMEIHASH_ = getDefaultInstance().getIMEIHASH();
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void setIMEIHASHBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iMEIHASH_ = value.toStringUtf8();
    }

    public static final int BOARD_FIELD_NUMBER = 2;
    private java.lang.String bOARD_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    public java.lang.String getBOARD() {
      return bOARD_;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBOARDBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bOARD_);
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    private void setBOARD(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bOARD_ = value;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    private void clearBOARD() {
      
      bOARD_ = getDefaultInstance().getBOARD();
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.html 
     * </pre>
     *
     * <code>optional string BOARD = 2;</code>
     */
    private void setBOARDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bOARD_ = value.toStringUtf8();
    }

    public static final int BRAND_FIELD_NUMBER = 3;
    private java.lang.String bRAND_;
    /**
     * <code>optional string BRAND = 3;</code>
     */
    public java.lang.String getBRAND() {
      return bRAND_;
    }
    /**
     * <code>optional string BRAND = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBRANDBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bRAND_);
    }
    /**
     * <code>optional string BRAND = 3;</code>
     */
    private void setBRAND(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bRAND_ = value;
    }
    /**
     * <code>optional string BRAND = 3;</code>
     */
    private void clearBRAND() {
      
      bRAND_ = getDefaultInstance().getBRAND();
    }
    /**
     * <code>optional string BRAND = 3;</code>
     */
    private void setBRANDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bRAND_ = value.toStringUtf8();
    }

    public static final int DEVICE_FIELD_NUMBER = 4;
    private java.lang.String dEVICE_;
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    public java.lang.String getDEVICE() {
      return dEVICE_;
    }
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDEVICEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(dEVICE_);
    }
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    private void setDEVICE(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dEVICE_ = value;
    }
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    private void clearDEVICE() {
      
      dEVICE_ = getDefaultInstance().getDEVICE();
    }
    /**
     * <code>optional string DEVICE = 4;</code>
     */
    private void setDEVICEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dEVICE_ = value.toStringUtf8();
    }

    public static final int HARDWARE_FIELD_NUMBER = 5;
    private java.lang.String hARDWARE_;
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    public java.lang.String getHARDWARE() {
      return hARDWARE_;
    }
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHARDWAREBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(hARDWARE_);
    }
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    private void setHARDWARE(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hARDWARE_ = value;
    }
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    private void clearHARDWARE() {
      
      hARDWARE_ = getDefaultInstance().getHARDWARE();
    }
    /**
     * <code>optional string HARDWARE = 5;</code>
     */
    private void setHARDWAREBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hARDWARE_ = value.toStringUtf8();
    }

    public static final int MANUFACTURER_FIELD_NUMBER = 6;
    private java.lang.String mANUFACTURER_;
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    public java.lang.String getMANUFACTURER() {
      return mANUFACTURER_;
    }
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMANUFACTURERBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mANUFACTURER_);
    }
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    private void setMANUFACTURER(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mANUFACTURER_ = value;
    }
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    private void clearMANUFACTURER() {
      
      mANUFACTURER_ = getDefaultInstance().getMANUFACTURER();
    }
    /**
     * <code>optional string MANUFACTURER = 6;</code>
     */
    private void setMANUFACTURERBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mANUFACTURER_ = value.toStringUtf8();
    }

    public static final int MODEL_FIELD_NUMBER = 7;
    private java.lang.String mODEL_;
    /**
     * <code>optional string MODEL = 7;</code>
     */
    public java.lang.String getMODEL() {
      return mODEL_;
    }
    /**
     * <code>optional string MODEL = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMODELBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mODEL_);
    }
    /**
     * <code>optional string MODEL = 7;</code>
     */
    private void setMODEL(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mODEL_ = value;
    }
    /**
     * <code>optional string MODEL = 7;</code>
     */
    private void clearMODEL() {
      
      mODEL_ = getDefaultInstance().getMODEL();
    }
    /**
     * <code>optional string MODEL = 7;</code>
     */
    private void setMODELBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mODEL_ = value.toStringUtf8();
    }

    public static final int PRODUCT_FIELD_NUMBER = 8;
    private java.lang.String pRODUCT_;
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    public java.lang.String getPRODUCT() {
      return pRODUCT_;
    }
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPRODUCTBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pRODUCT_);
    }
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    private void setPRODUCT(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pRODUCT_ = value;
    }
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    private void clearPRODUCT() {
      
      pRODUCT_ = getDefaultInstance().getPRODUCT();
    }
    /**
     * <code>optional string PRODUCT = 8;</code>
     */
    private void setPRODUCTBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pRODUCT_ = value.toStringUtf8();
    }

    public static final int NETWORK_COUNTRY_ISO_FIELD_NUMBER = 9;
    private java.lang.String nETWORKCOUNTRYISO_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    public java.lang.String getNETWORKCOUNTRYISO() {
      return nETWORKCOUNTRYISO_;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKCOUNTRYISOBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nETWORKCOUNTRYISO_);
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    private void setNETWORKCOUNTRYISO(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nETWORKCOUNTRYISO_ = value;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    private void clearNETWORKCOUNTRYISO() {
      
      nETWORKCOUNTRYISO_ = getDefaultInstance().getNETWORKCOUNTRYISO();
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
     */
    private void setNETWORKCOUNTRYISOBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nETWORKCOUNTRYISO_ = value.toStringUtf8();
    }

    public static final int NETWORK_OPERATOR_CODE_FIELD_NUMBER = 10;
    private java.lang.String nETWORKOPERATORCODE_;
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    public java.lang.String getNETWORKOPERATORCODE() {
      return nETWORKOPERATORCODE_;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKOPERATORCODEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nETWORKOPERATORCODE_);
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    private void setNETWORKOPERATORCODE(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nETWORKOPERATORCODE_ = value;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    private void clearNETWORKOPERATORCODE() {
      
      nETWORKOPERATORCODE_ = getDefaultInstance().getNETWORKOPERATORCODE();
    }
    /**
     * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
     */
    private void setNETWORKOPERATORCODEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nETWORKOPERATORCODE_ = value.toStringUtf8();
    }

    public static final int NETWORK_OPERATOR_NAME_FIELD_NUMBER = 11;
    private java.lang.String nETWORKOPERATORNAME_;
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    public java.lang.String getNETWORKOPERATORNAME() {
      return nETWORKOPERATORNAME_;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    public com.google.protobuf.ByteString
        getNETWORKOPERATORNAMEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nETWORKOPERATORNAME_);
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    private void setNETWORKOPERATORNAME(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nETWORKOPERATORNAME_ = value;
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    private void clearNETWORKOPERATORNAME() {
      
      nETWORKOPERATORNAME_ = getDefaultInstance().getNETWORKOPERATORNAME();
    }
    /**
     * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
     */
    private void setNETWORKOPERATORNAMEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nETWORKOPERATORNAME_ = value.toStringUtf8();
    }

    public static final int PHONE_TYPE_FIELD_NUMBER = 12;
    private java.lang.String pHONETYPE_;
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    public java.lang.String getPHONETYPE() {
      return pHONETYPE_;
    }
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    public com.google.protobuf.ByteString
        getPHONETYPEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pHONETYPE_);
    }
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    private void setPHONETYPE(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pHONETYPE_ = value;
    }
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    private void clearPHONETYPE() {
      
      pHONETYPE_ = getDefaultInstance().getPHONETYPE();
    }
    /**
     * <code>optional string PHONE_TYPE = 12;</code>
     */
    private void setPHONETYPEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pHONETYPE_ = value.toStringUtf8();
    }

    public static final int SIM_COUNTRY_ISO_FIELD_NUMBER = 13;
    private java.lang.String sIMCOUNTRYISO_;
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    public java.lang.String getSIMCOUNTRYISO() {
      return sIMCOUNTRYISO_;
    }
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    public com.google.protobuf.ByteString
        getSIMCOUNTRYISOBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sIMCOUNTRYISO_);
    }
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    private void setSIMCOUNTRYISO(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sIMCOUNTRYISO_ = value;
    }
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    private void clearSIMCOUNTRYISO() {
      
      sIMCOUNTRYISO_ = getDefaultInstance().getSIMCOUNTRYISO();
    }
    /**
     * <code>optional string SIM_COUNTRY_ISO = 13;</code>
     */
    private void setSIMCOUNTRYISOBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sIMCOUNTRYISO_ = value.toStringUtf8();
    }

    public static final int SIM_OPERATOR_FIELD_NUMBER = 14;
    private java.lang.String sIMOPERATOR_;
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    public java.lang.String getSIMOPERATOR() {
      return sIMOPERATOR_;
    }
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    public com.google.protobuf.ByteString
        getSIMOPERATORBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sIMOPERATOR_);
    }
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    private void setSIMOPERATOR(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sIMOPERATOR_ = value;
    }
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    private void clearSIMOPERATOR() {
      
      sIMOPERATOR_ = getDefaultInstance().getSIMOPERATOR();
    }
    /**
     * <code>optional string SIM_OPERATOR = 14;</code>
     */
    private void setSIMOPERATORBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sIMOPERATOR_ = value.toStringUtf8();
    }

    public static final int SIM_OPERATOR_NAME_FIELD_NUMBER = 15;
    private java.lang.String sIMOPERATORNAME_;
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    public java.lang.String getSIMOPERATORNAME() {
      return sIMOPERATORNAME_;
    }
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    public com.google.protobuf.ByteString
        getSIMOPERATORNAMEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sIMOPERATORNAME_);
    }
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    private void setSIMOPERATORNAME(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sIMOPERATORNAME_ = value;
    }
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    private void clearSIMOPERATORNAME() {
      
      sIMOPERATORNAME_ = getDefaultInstance().getSIMOPERATORNAME();
    }
    /**
     * <code>optional string SIM_OPERATOR_NAME = 15;</code>
     */
    private void setSIMOPERATORNAMEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sIMOPERATORNAME_ = value.toStringUtf8();
    }

    public static final int RELEASE_FIELD_NUMBER = 16;
    private java.lang.String rELEASE_;
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    public java.lang.String getRELEASE() {
      return rELEASE_;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    public com.google.protobuf.ByteString
        getRELEASEBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(rELEASE_);
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    private void setRELEASE(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rELEASE_ = value;
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    private void clearRELEASE() {
      
      rELEASE_ = getDefaultInstance().getRELEASE();
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/os/Build.VERSION.html 
     * </pre>
     *
     * <code>optional string RELEASE = 16;</code>
     */
    private void setRELEASEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rELEASE_ = value.toStringUtf8();
    }

    public static final int SDK_INT_FIELD_NUMBER = 17;
    private java.lang.String sDKINT_;
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    public java.lang.String getSDKINT() {
      return sDKINT_;
    }
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    public com.google.protobuf.ByteString
        getSDKINTBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sDKINT_);
    }
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    private void setSDKINT(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sDKINT_ = value;
    }
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    private void clearSDKINT() {
      
      sDKINT_ = getDefaultInstance().getSDKINT();
    }
    /**
     * <code>optional string SDK_INT = 17;</code>
     */
    private void setSDKINTBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sDKINT_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!iMEIHASH_.isEmpty()) {
        output.writeString(1, getIMEIHASH());
      }
      if (!bOARD_.isEmpty()) {
        output.writeString(2, getBOARD());
      }
      if (!bRAND_.isEmpty()) {
        output.writeString(3, getBRAND());
      }
      if (!dEVICE_.isEmpty()) {
        output.writeString(4, getDEVICE());
      }
      if (!hARDWARE_.isEmpty()) {
        output.writeString(5, getHARDWARE());
      }
      if (!mANUFACTURER_.isEmpty()) {
        output.writeString(6, getMANUFACTURER());
      }
      if (!mODEL_.isEmpty()) {
        output.writeString(7, getMODEL());
      }
      if (!pRODUCT_.isEmpty()) {
        output.writeString(8, getPRODUCT());
      }
      if (!nETWORKCOUNTRYISO_.isEmpty()) {
        output.writeString(9, getNETWORKCOUNTRYISO());
      }
      if (!nETWORKOPERATORCODE_.isEmpty()) {
        output.writeString(10, getNETWORKOPERATORCODE());
      }
      if (!nETWORKOPERATORNAME_.isEmpty()) {
        output.writeString(11, getNETWORKOPERATORNAME());
      }
      if (!pHONETYPE_.isEmpty()) {
        output.writeString(12, getPHONETYPE());
      }
      if (!sIMCOUNTRYISO_.isEmpty()) {
        output.writeString(13, getSIMCOUNTRYISO());
      }
      if (!sIMOPERATOR_.isEmpty()) {
        output.writeString(14, getSIMOPERATOR());
      }
      if (!sIMOPERATORNAME_.isEmpty()) {
        output.writeString(15, getSIMOPERATORNAME());
      }
      if (!rELEASE_.isEmpty()) {
        output.writeString(16, getRELEASE());
      }
      if (!sDKINT_.isEmpty()) {
        output.writeString(17, getSDKINT());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!iMEIHASH_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIMEIHASH());
      }
      if (!bOARD_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getBOARD());
      }
      if (!bRAND_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getBRAND());
      }
      if (!dEVICE_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getDEVICE());
      }
      if (!hARDWARE_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getHARDWARE());
      }
      if (!mANUFACTURER_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getMANUFACTURER());
      }
      if (!mODEL_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getMODEL());
      }
      if (!pRODUCT_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getPRODUCT());
      }
      if (!nETWORKCOUNTRYISO_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getNETWORKCOUNTRYISO());
      }
      if (!nETWORKOPERATORCODE_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getNETWORKOPERATORCODE());
      }
      if (!nETWORKOPERATORNAME_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getNETWORKOPERATORNAME());
      }
      if (!pHONETYPE_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getPHONETYPE());
      }
      if (!sIMCOUNTRYISO_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getSIMCOUNTRYISO());
      }
      if (!sIMOPERATOR_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getSIMOPERATOR());
      }
      if (!sIMOPERATORNAME_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(15, getSIMOPERATORNAME());
      }
      if (!rELEASE_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(16, getRELEASE());
      }
      if (!sDKINT_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(17, getSDKINT());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code RegisterDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice, Builder> implements
        // @@protoc_insertion_point(builder_implements:RegisterDevice)
        edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDeviceOrBuilder {
      // Construct using edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public java.lang.String getIMEIHASH() {
        return instance.getIMEIHASH();
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIMEIHASHBytes() {
        return instance.getIMEIHASHBytes();
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASH(
          java.lang.String value) {
        copyOnWrite();
        instance.setIMEIHASH(value);
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder clearIMEIHASH() {
        copyOnWrite();
        instance.clearIMEIHASH();
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASHBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIMEIHASHBytes(value);
        return this;
      }

      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public java.lang.String getBOARD() {
        return instance.getBOARD();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBOARDBytes() {
        return instance.getBOARDBytes();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public Builder setBOARD(
          java.lang.String value) {
        copyOnWrite();
        instance.setBOARD(value);
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public Builder clearBOARD() {
        copyOnWrite();
        instance.clearBOARD();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.html 
       * </pre>
       *
       * <code>optional string BOARD = 2;</code>
       */
      public Builder setBOARDBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBOARDBytes(value);
        return this;
      }

      /**
       * <code>optional string BRAND = 3;</code>
       */
      public java.lang.String getBRAND() {
        return instance.getBRAND();
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBRANDBytes() {
        return instance.getBRANDBytes();
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public Builder setBRAND(
          java.lang.String value) {
        copyOnWrite();
        instance.setBRAND(value);
        return this;
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public Builder clearBRAND() {
        copyOnWrite();
        instance.clearBRAND();
        return this;
      }
      /**
       * <code>optional string BRAND = 3;</code>
       */
      public Builder setBRANDBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBRANDBytes(value);
        return this;
      }

      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public java.lang.String getDEVICE() {
        return instance.getDEVICE();
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDEVICEBytes() {
        return instance.getDEVICEBytes();
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public Builder setDEVICE(
          java.lang.String value) {
        copyOnWrite();
        instance.setDEVICE(value);
        return this;
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public Builder clearDEVICE() {
        copyOnWrite();
        instance.clearDEVICE();
        return this;
      }
      /**
       * <code>optional string DEVICE = 4;</code>
       */
      public Builder setDEVICEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDEVICEBytes(value);
        return this;
      }

      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public java.lang.String getHARDWARE() {
        return instance.getHARDWARE();
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHARDWAREBytes() {
        return instance.getHARDWAREBytes();
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public Builder setHARDWARE(
          java.lang.String value) {
        copyOnWrite();
        instance.setHARDWARE(value);
        return this;
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public Builder clearHARDWARE() {
        copyOnWrite();
        instance.clearHARDWARE();
        return this;
      }
      /**
       * <code>optional string HARDWARE = 5;</code>
       */
      public Builder setHARDWAREBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHARDWAREBytes(value);
        return this;
      }

      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public java.lang.String getMANUFACTURER() {
        return instance.getMANUFACTURER();
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMANUFACTURERBytes() {
        return instance.getMANUFACTURERBytes();
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public Builder setMANUFACTURER(
          java.lang.String value) {
        copyOnWrite();
        instance.setMANUFACTURER(value);
        return this;
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public Builder clearMANUFACTURER() {
        copyOnWrite();
        instance.clearMANUFACTURER();
        return this;
      }
      /**
       * <code>optional string MANUFACTURER = 6;</code>
       */
      public Builder setMANUFACTURERBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMANUFACTURERBytes(value);
        return this;
      }

      /**
       * <code>optional string MODEL = 7;</code>
       */
      public java.lang.String getMODEL() {
        return instance.getMODEL();
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMODELBytes() {
        return instance.getMODELBytes();
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public Builder setMODEL(
          java.lang.String value) {
        copyOnWrite();
        instance.setMODEL(value);
        return this;
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public Builder clearMODEL() {
        copyOnWrite();
        instance.clearMODEL();
        return this;
      }
      /**
       * <code>optional string MODEL = 7;</code>
       */
      public Builder setMODELBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMODELBytes(value);
        return this;
      }

      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public java.lang.String getPRODUCT() {
        return instance.getPRODUCT();
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPRODUCTBytes() {
        return instance.getPRODUCTBytes();
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public Builder setPRODUCT(
          java.lang.String value) {
        copyOnWrite();
        instance.setPRODUCT(value);
        return this;
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public Builder clearPRODUCT() {
        copyOnWrite();
        instance.clearPRODUCT();
        return this;
      }
      /**
       * <code>optional string PRODUCT = 8;</code>
       */
      public Builder setPRODUCTBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPRODUCTBytes(value);
        return this;
      }

      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public java.lang.String getNETWORKCOUNTRYISO() {
        return instance.getNETWORKCOUNTRYISO();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKCOUNTRYISOBytes() {
        return instance.getNETWORKCOUNTRYISOBytes();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public Builder setNETWORKCOUNTRYISO(
          java.lang.String value) {
        copyOnWrite();
        instance.setNETWORKCOUNTRYISO(value);
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public Builder clearNETWORKCOUNTRYISO() {
        copyOnWrite();
        instance.clearNETWORKCOUNTRYISO();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
       * </pre>
       *
       * <code>optional string NETWORK_COUNTRY_ISO = 9;</code>
       */
      public Builder setNETWORKCOUNTRYISOBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNETWORKCOUNTRYISOBytes(value);
        return this;
      }

      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public java.lang.String getNETWORKOPERATORCODE() {
        return instance.getNETWORKOPERATORCODE();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKOPERATORCODEBytes() {
        return instance.getNETWORKOPERATORCODEBytes();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public Builder setNETWORKOPERATORCODE(
          java.lang.String value) {
        copyOnWrite();
        instance.setNETWORKOPERATORCODE(value);
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public Builder clearNETWORKOPERATORCODE() {
        copyOnWrite();
        instance.clearNETWORKOPERATORCODE();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_CODE = 10;</code>
       */
      public Builder setNETWORKOPERATORCODEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNETWORKOPERATORCODEBytes(value);
        return this;
      }

      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public java.lang.String getNETWORKOPERATORNAME() {
        return instance.getNETWORKOPERATORNAME();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public com.google.protobuf.ByteString
          getNETWORKOPERATORNAMEBytes() {
        return instance.getNETWORKOPERATORNAMEBytes();
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public Builder setNETWORKOPERATORNAME(
          java.lang.String value) {
        copyOnWrite();
        instance.setNETWORKOPERATORNAME(value);
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public Builder clearNETWORKOPERATORNAME() {
        copyOnWrite();
        instance.clearNETWORKOPERATORNAME();
        return this;
      }
      /**
       * <code>optional string NETWORK_OPERATOR_NAME = 11;</code>
       */
      public Builder setNETWORKOPERATORNAMEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNETWORKOPERATORNAMEBytes(value);
        return this;
      }

      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public java.lang.String getPHONETYPE() {
        return instance.getPHONETYPE();
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPHONETYPEBytes() {
        return instance.getPHONETYPEBytes();
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public Builder setPHONETYPE(
          java.lang.String value) {
        copyOnWrite();
        instance.setPHONETYPE(value);
        return this;
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public Builder clearPHONETYPE() {
        copyOnWrite();
        instance.clearPHONETYPE();
        return this;
      }
      /**
       * <code>optional string PHONE_TYPE = 12;</code>
       */
      public Builder setPHONETYPEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPHONETYPEBytes(value);
        return this;
      }

      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public java.lang.String getSIMCOUNTRYISO() {
        return instance.getSIMCOUNTRYISO();
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public com.google.protobuf.ByteString
          getSIMCOUNTRYISOBytes() {
        return instance.getSIMCOUNTRYISOBytes();
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public Builder setSIMCOUNTRYISO(
          java.lang.String value) {
        copyOnWrite();
        instance.setSIMCOUNTRYISO(value);
        return this;
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public Builder clearSIMCOUNTRYISO() {
        copyOnWrite();
        instance.clearSIMCOUNTRYISO();
        return this;
      }
      /**
       * <code>optional string SIM_COUNTRY_ISO = 13;</code>
       */
      public Builder setSIMCOUNTRYISOBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSIMCOUNTRYISOBytes(value);
        return this;
      }

      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public java.lang.String getSIMOPERATOR() {
        return instance.getSIMOPERATOR();
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public com.google.protobuf.ByteString
          getSIMOPERATORBytes() {
        return instance.getSIMOPERATORBytes();
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public Builder setSIMOPERATOR(
          java.lang.String value) {
        copyOnWrite();
        instance.setSIMOPERATOR(value);
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public Builder clearSIMOPERATOR() {
        copyOnWrite();
        instance.clearSIMOPERATOR();
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR = 14;</code>
       */
      public Builder setSIMOPERATORBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSIMOPERATORBytes(value);
        return this;
      }

      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public java.lang.String getSIMOPERATORNAME() {
        return instance.getSIMOPERATORNAME();
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public com.google.protobuf.ByteString
          getSIMOPERATORNAMEBytes() {
        return instance.getSIMOPERATORNAMEBytes();
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public Builder setSIMOPERATORNAME(
          java.lang.String value) {
        copyOnWrite();
        instance.setSIMOPERATORNAME(value);
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public Builder clearSIMOPERATORNAME() {
        copyOnWrite();
        instance.clearSIMOPERATORNAME();
        return this;
      }
      /**
       * <code>optional string SIM_OPERATOR_NAME = 15;</code>
       */
      public Builder setSIMOPERATORNAMEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSIMOPERATORNAMEBytes(value);
        return this;
      }

      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public java.lang.String getRELEASE() {
        return instance.getRELEASE();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public com.google.protobuf.ByteString
          getRELEASEBytes() {
        return instance.getRELEASEBytes();
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public Builder setRELEASE(
          java.lang.String value) {
        copyOnWrite();
        instance.setRELEASE(value);
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public Builder clearRELEASE() {
        copyOnWrite();
        instance.clearRELEASE();
        return this;
      }
      /**
       * <pre>
       * https://developer.android.com/reference/android/os/Build.VERSION.html 
       * </pre>
       *
       * <code>optional string RELEASE = 16;</code>
       */
      public Builder setRELEASEBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRELEASEBytes(value);
        return this;
      }

      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public java.lang.String getSDKINT() {
        return instance.getSDKINT();
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public com.google.protobuf.ByteString
          getSDKINTBytes() {
        return instance.getSDKINTBytes();
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public Builder setSDKINT(
          java.lang.String value) {
        copyOnWrite();
        instance.setSDKINT(value);
        return this;
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public Builder clearSDKINT() {
        copyOnWrite();
        instance.clearSDKINT();
        return this;
      }
      /**
       * <code>optional string SDK_INT = 17;</code>
       */
      public Builder setSDKINTBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSDKINTBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RegisterDevice)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice other = (edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice) arg1;
          iMEIHASH_ = visitor.visitString(!iMEIHASH_.isEmpty(), iMEIHASH_,
              !other.iMEIHASH_.isEmpty(), other.iMEIHASH_);
          bOARD_ = visitor.visitString(!bOARD_.isEmpty(), bOARD_,
              !other.bOARD_.isEmpty(), other.bOARD_);
          bRAND_ = visitor.visitString(!bRAND_.isEmpty(), bRAND_,
              !other.bRAND_.isEmpty(), other.bRAND_);
          dEVICE_ = visitor.visitString(!dEVICE_.isEmpty(), dEVICE_,
              !other.dEVICE_.isEmpty(), other.dEVICE_);
          hARDWARE_ = visitor.visitString(!hARDWARE_.isEmpty(), hARDWARE_,
              !other.hARDWARE_.isEmpty(), other.hARDWARE_);
          mANUFACTURER_ = visitor.visitString(!mANUFACTURER_.isEmpty(), mANUFACTURER_,
              !other.mANUFACTURER_.isEmpty(), other.mANUFACTURER_);
          mODEL_ = visitor.visitString(!mODEL_.isEmpty(), mODEL_,
              !other.mODEL_.isEmpty(), other.mODEL_);
          pRODUCT_ = visitor.visitString(!pRODUCT_.isEmpty(), pRODUCT_,
              !other.pRODUCT_.isEmpty(), other.pRODUCT_);
          nETWORKCOUNTRYISO_ = visitor.visitString(!nETWORKCOUNTRYISO_.isEmpty(), nETWORKCOUNTRYISO_,
              !other.nETWORKCOUNTRYISO_.isEmpty(), other.nETWORKCOUNTRYISO_);
          nETWORKOPERATORCODE_ = visitor.visitString(!nETWORKOPERATORCODE_.isEmpty(), nETWORKOPERATORCODE_,
              !other.nETWORKOPERATORCODE_.isEmpty(), other.nETWORKOPERATORCODE_);
          nETWORKOPERATORNAME_ = visitor.visitString(!nETWORKOPERATORNAME_.isEmpty(), nETWORKOPERATORNAME_,
              !other.nETWORKOPERATORNAME_.isEmpty(), other.nETWORKOPERATORNAME_);
          pHONETYPE_ = visitor.visitString(!pHONETYPE_.isEmpty(), pHONETYPE_,
              !other.pHONETYPE_.isEmpty(), other.pHONETYPE_);
          sIMCOUNTRYISO_ = visitor.visitString(!sIMCOUNTRYISO_.isEmpty(), sIMCOUNTRYISO_,
              !other.sIMCOUNTRYISO_.isEmpty(), other.sIMCOUNTRYISO_);
          sIMOPERATOR_ = visitor.visitString(!sIMOPERATOR_.isEmpty(), sIMOPERATOR_,
              !other.sIMOPERATOR_.isEmpty(), other.sIMOPERATOR_);
          sIMOPERATORNAME_ = visitor.visitString(!sIMOPERATORNAME_.isEmpty(), sIMOPERATORNAME_,
              !other.sIMOPERATORNAME_.isEmpty(), other.sIMOPERATORNAME_);
          rELEASE_ = visitor.visitString(!rELEASE_.isEmpty(), rELEASE_,
              !other.rELEASE_.isEmpty(), other.rELEASE_);
          sDKINT_ = visitor.visitString(!sDKINT_.isEmpty(), sDKINT_,
              !other.sDKINT_.isEmpty(), other.sDKINT_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  iMEIHASH_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  bOARD_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  bRAND_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  dEVICE_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  hARDWARE_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  mANUFACTURER_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  mODEL_ = s;
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  pRODUCT_ = s;
                  break;
                }
                case 74: {
                  String s = input.readStringRequireUtf8();

                  nETWORKCOUNTRYISO_ = s;
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();

                  nETWORKOPERATORCODE_ = s;
                  break;
                }
                case 90: {
                  String s = input.readStringRequireUtf8();

                  nETWORKOPERATORNAME_ = s;
                  break;
                }
                case 98: {
                  String s = input.readStringRequireUtf8();

                  pHONETYPE_ = s;
                  break;
                }
                case 106: {
                  String s = input.readStringRequireUtf8();

                  sIMCOUNTRYISO_ = s;
                  break;
                }
                case 114: {
                  String s = input.readStringRequireUtf8();

                  sIMOPERATOR_ = s;
                  break;
                }
                case 122: {
                  String s = input.readStringRequireUtf8();

                  sIMOPERATORNAME_ = s;
                  break;
                }
                case 130: {
                  String s = input.readStringRequireUtf8();

                  rELEASE_ = s;
                  break;
                }
                case 138: {
                  String s = input.readStringRequireUtf8();

                  sDKINT_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:RegisterDevice)
    private static final edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RegisterDevice();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static edu.buffalo.cse.ubwins.cellmon.RegisterDeviceOuterClass.RegisterDevice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RegisterDevice> PARSER;

    public static com.google.protobuf.Parser<RegisterDevice> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
